#!/usr/bin/env bash
# bootstrap.sh — Runtime onboarding script
# Reads onboard.yml at startup via python3 + PyYAML.
# Generated by project-onboard skill.
#
# Usage:
#   ./bootstrap.sh                    # prod mode (default), interactive
#   ./bootstrap.sh --mode dev         # maintainer/contributor setup
#   ./bootstrap.sh --mode prod        # end-user setup and deploy
#   ./bootstrap.sh --non-interactive  # use all defaults, no prompts
#   ./bootstrap.sh --check-only       # run validation checks only
#   ./bootstrap.sh --help             # show usage

set -euo pipefail

# ─── Ensure common tool paths are available ──────────────────────────────────

for p in "$HOME/.local/bin" "/usr/local/bin" "$HOME/bin"; do
    [[ -d "$p" ]] && [[ ":$PATH:" != *":$p:"* ]] && export PATH="$p:$PATH"
done

# Clear proxy vars that may be injected by IDE/editor shells — they break
# AWS CLI and other tools that need direct internet access.
unset HTTP_PROXY HTTPS_PROXY http_proxy https_proxy NO_PROXY no_proxy 2>/dev/null || true

# ─── Colors ──────────────────────────────────────────────────────────────────

if [[ -t 1 ]]; then
    RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
    BLUE='\033[0;34m'; BOLD='\033[1m'; RESET='\033[0m'
else
    RED=''; GREEN=''; YELLOW=''; BLUE=''; BOLD=''; RESET=''
fi

info()    { echo -e "${BLUE}[INFO]${RESET} $*"; }
ok()      { echo -e "  ${GREEN}[OK]${RESET}      $*"; }
installing() { echo -e "  ${YELLOW}[INSTALL]${RESET} $*"; }
fail()    { echo -e "  ${RED}[FAIL]${RESET}    $*"; }
pass()    { echo -e "  ${GREEN}[PASS]${RESET}    $*"; }
warn_msg(){ echo -e "  ${YELLOW}[WARN]${RESET}    $*"; }
skip()    { echo -e "  ${GREEN}[SKIP]${RESET}    $*"; }
run_msg() { echo -e "  ${BLUE}[RUN]${RESET}     $*"; }

# ─── Argument Parsing ────────────────────────────────────────────────────────

MODE="prod"
NON_INTERACTIVE=false
CHECK_ONLY=false

usage() {
    cat <<'EOF'
LINBIT Edge Storage Workshop Bootstrap (reads onboard.yml)

Usage: ./bootstrap.sh [OPTIONS]

Options:
  --mode dev|prod    dev = maintainer setup, prod = end-user deploy (default: prod)
  --non-interactive  Accept all defaults without prompting
  --check-only       Run validation checks only
  --help             Show this help

EOF
    exit 0
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --mode)       MODE="${2:-prod}"; shift 2 ;;
        --non-interactive) NON_INTERACTIVE=true; shift ;;
        --check-only) CHECK_ONLY=true; shift ;;
        --help|-h)    usage ;;
        *)            echo "Unknown option: $1"; usage ;;
    esac
done

# ─── Dependency Checks ──────────────────────────────────────────────────────

if ! command -v python3 &>/dev/null; then
    echo "ERROR: python3 is required but not found."
    echo "  RHEL/Fedora: sudo dnf install -y python3"
    echo "  Debian/Ubuntu: sudo apt-get install -y python3"
    echo "  macOS: brew install python3"
    exit 1
fi

if ! python3 -c "import yaml" 2>/dev/null; then
    echo "ERROR: PyYAML is required but not installed."
    echo "  RHEL/Fedora: sudo dnf install -y python3-pyyaml"
    echo "  Debian/Ubuntu: sudo apt-get install -y python3-yaml"
    echo "  pip: pip3 install pyyaml"
    echo "  macOS: pip3 install pyyaml"
    exit 1
fi

# ─── Manifest Discovery ─────────────────────────────────────────────────────

MANIFEST=""
for candidate in onboard.yml onboard.json agnosticd/onboard.yml \
                 agnosticd/onboard.json .onboard.yml .onboard.json; do
    if [[ -f "$candidate" ]]; then
        MANIFEST="$candidate"
        break
    fi
done

if [[ -z "$MANIFEST" ]]; then
    echo "ERROR: No onboard.yml found in this directory."
    echo "  Searched: onboard.yml, onboard.json, agnosticd/onboard.yml,"
    echo "           agnosticd/onboard.json, .onboard.yml, .onboard.json"
    exit 1
fi

# ─── YAML to JSON Conversion ────────────────────────────────────────────────

MANIFEST_JSON=$(mktemp)
trap 'rm -f "$MANIFEST_JSON"' EXIT

python3 -c "
import yaml, json, sys
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
json.dump(data, sys.stdout)
" "$MANIFEST" > "$MANIFEST_JSON"

# ─── JSON Query Helper ──────────────────────────────────────────────────────

manifest_get() {
    local query="$1"
    if command -v jq &>/dev/null; then
        jq -r "$query // empty" "$MANIFEST_JSON"
    else
        python3 -c "
import json, sys, re

with open(sys.argv[2]) as f:
    data = json.load(f)

query = sys.argv[1]
result = data

for token in re.findall(r'\.(\w+)|\[(\d+)\]', query):
    key, idx = token
    if result is None:
        break
    if key:
        result = result.get(key) if isinstance(result, dict) else None
    elif idx:
        i = int(idx)
        result = result[i] if isinstance(result, list) and i < len(result) else None

if result is None or result == '':
    sys.exit(0)
if isinstance(result, (dict, list)):
    json.dump(result, sys.stdout)
elif isinstance(result, bool):
    print(str(result).lower())
else:
    print(result)
" "$query" "$MANIFEST_JSON"
    fi
}

manifest_len() {
    local query="$1"
    if command -v jq &>/dev/null; then
        jq -r "($query // []) | length" "$MANIFEST_JSON"
    else
        python3 -c "
import json, sys, re

with open(sys.argv[2]) as f:
    data = json.load(f)

query = sys.argv[1]
result = data
for token in re.findall(r'\.(\w+)|\[(\d+)\]', query):
    key, idx = token
    if result is None:
        break
    if key:
        result = result.get(key) if isinstance(result, dict) else None
    elif idx:
        i = int(idx)
        result = result[i] if isinstance(result, list) and i < len(result) else None

if isinstance(result, list):
    print(len(result))
else:
    print(0)
" "$query" "$MANIFEST_JSON"
    fi
}

# ─── Platform Detection ─────────────────────────────────────────────────────

detect_distro() {
    if [[ "$(uname -s)" == "Darwin" ]]; then
        echo "macos"
        return
    fi
    if [[ -f /etc/os-release ]]; then
        local id version_id major
        id="$(. /etc/os-release && echo "${ID:-}")"
        version_id="$(. /etc/os-release && echo "${VERSION_ID:-}")"
        major="${version_id%%.*}"
        case "$id" in
            rhel|redhat|centos) echo "rhel${major}" ;;
            fedora)             echo "fedora" ;;
            debian|ubuntu)      echo "debian" ;;
            *)                  echo "unknown" ;;
        esac
    else
        echo "unknown"
    fi
}

# ─── Version Comparison ─────────────────────────────────────────────────────

version_gte() {
    local have="$1" need="$2"
    local IFS='.'
    local -a have_parts=($have) need_parts=($need)
    local i
    for (( i=0; i<${#need_parts[@]}; i++ )); do
        local h="${have_parts[$i]:-0}"
        local n="${need_parts[$i]:-0}"
        if (( h > n )); then return 0; fi
        if (( h < n )); then return 1; fi
    done
    return 0
}

# ─── Variable Store ─────────────────────────────────────────────────────────

declare -A VARS
CONFIG_FROM_FILE=false

substitute_vars() {
    local text="$1"
    local key val
    for key in "${!VARS[@]}"; do
        val="${VARS[$key]}"
        text="${text//\$\{${key}\}/${val}}"
    done
    echo "$text"
}

# Expand ~ in path-like config values
expand_path_vars() {
    local key
    for key in agnosticd_root pull_secret_path; do
        if [[ -n "${VARS[$key]+_}" ]]; then
            VARS["$key"]="${VARS[$key]/#\~/$HOME}"
        fi
    done
}

secrets_file_path() {
    local root="${VARS[agnosticd_root]:-}"
    local account="${VARS[account]:-}"
    [[ -n "$root" && -n "$account" ]] || { echo ""; return; }
    echo "${root}/../agnosticd-v2-secrets/secrets-${account}.yml"
}

# Returns: missing | placeholders | ok
secrets_status() {
    local path
    path="$(secrets_file_path)"
    if [[ -z "$path" || ! -f "$path" ]]; then
        echo "missing"
        return
    fi
    if grep -q '<Your' "$path" 2>/dev/null || ! grep -q 'aws_access_key_id:' "$path" 2>/dev/null; then
        echo "placeholders"
        return
    fi
    echo "ok"
}

choices_to_str() {
    local choices="$1"
    if [[ -z "$choices" || "$choices" == "null" ]]; then
        echo ""
        return
    fi
    echo "$choices" | python3 -c "
import json, sys
arr = json.load(sys.stdin)
print(','.join(str(x) for x in arr)) if isinstance(arr, list) else print('')
" 2>/dev/null || echo ""
}

# ─── Prompt Helper ──────────────────────────────────────────────────────────

prompt_for() {
    local key="$1" prompt_text="$2" default="$3"
    local choices="${4:-}" required="${5:-false}"

    if [[ "$NON_INTERACTIVE" == "true" ]]; then
        VARS["$key"]="$default"
        return
    fi

    while true; do
        local display="  ${prompt_text}"
        [[ -n "$default" ]] && display+=" [${default}]"
        [[ -n "$choices" ]] && display+=" (${choices})"
        display+=": "

        read -rp "$display" value
        value="${value:-$default}"

        if [[ -n "$choices" && -n "$value" ]]; then
            local valid=false
            IFS=',' read -ra choice_arr <<< "$choices"
            for c in "${choice_arr[@]}"; do
                [[ "$value" == "$c" ]] && valid=true
            done
            if [[ "$valid" != "true" ]]; then
                echo "    Invalid choice. Options: $choices"
                continue
            fi
        fi

        if [[ "$required" == "true" && -z "$value" ]]; then
            echo "    This field is required."
            continue
        fi

        VARS["$key"]="$value"
        return
    done
}

# ─── Phase: Prerequisites ───────────────────────────────────────────────────

install_prerequisites() {
    local distro="$1" prereqs_path="$2" label="$3"
    local count
    count="$(manifest_len "$prereqs_path")"
    if (( count == 0 )); then return 0; fi

    echo ""
    echo -e "${BOLD}--- ${label} ---${RESET}"
    echo ""

    local i name check_cmd version_regex min_version install_cmd fallback_msg
    for (( i=0; i<count; i++ )); do
        name="$(manifest_get "${prereqs_path}[$i].name")"
        check_cmd="$(manifest_get "${prereqs_path}[$i].check_command")"
        version_regex="$(manifest_get "${prereqs_path}[$i].version_regex")"
        min_version="$(manifest_get "${prereqs_path}[$i].min_version")"

        install_cmd="$(manifest_get "${prereqs_path}[$i].install.${distro}")"
        if [[ -z "$install_cmd" ]]; then
            install_cmd="$(manifest_get "${prereqs_path}[$i].install.fallback")"
        fi

        local output=""
        if output=$(eval "$check_cmd" 2>&1); then
            if [[ -n "$version_regex" && -n "$min_version" ]]; then
                local version
                version=$(echo "$output" | python3 -c "
import re, sys
text = sys.stdin.read()
m = re.search(sys.argv[1], text)
print(m.group(1) if m else '0.0')
" "$version_regex" 2>/dev/null || echo "0.0")
                if version_gte "$version" "$min_version"; then
                    ok "${name} ${version} (>= ${min_version})"
                    continue
                else
                    installing "${name} ${version} is too old (need >= ${min_version})"
                fi
            else
                ok "${name} installed"
                continue
            fi
        else
            installing "${name} not found"
        fi

        if [[ -z "$install_cmd" ]]; then
            fail "No install command for ${name} on ${distro}."
            fallback_msg="$(manifest_get "${prereqs_path}[$i].install.fallback")"
            [[ -n "$fallback_msg" ]] && echo "      $fallback_msg"
            return 1
        fi

        echo "            -> Running: ${install_cmd}"
        if ! eval "$install_cmd"; then
            fail "Failed to install ${name}"
            return 1
        fi
        ok "${name} installed"
    done
}

# ─── Phase: Setup Steps ─────────────────────────────────────────────────────

run_setup_steps() {
    local count
    count="$(manifest_len ".setup_steps")"
    if (( count == 0 )); then return 0; fi

    echo ""
    echo -e "${BOLD}--- Setup Steps ---${RESET}"
    echo ""

    local i name check action prompt_var prompt_text default_val
    for (( i=0; i<count; i++ )); do
        name="$(manifest_get ".setup_steps[$i].name")"
        check="$(manifest_get ".setup_steps[$i].check")"
        action="$(manifest_get ".setup_steps[$i].action")"
        prompt_var="$(manifest_get ".setup_steps[$i].prompt_var")"
        prompt_text="$(manifest_get ".setup_steps[$i].prompt")"
        default_val="$(manifest_get ".setup_steps[$i].default")"

        # Config wizard already collected values; only prompt if still unset
        if [[ -n "$prompt_var" && -z "${VARS[$prompt_var]+_}" ]]; then
            prompt_for "$prompt_var" "${prompt_text:-$prompt_var}" "${default_val:-}"
            local raw="${VARS[$prompt_var]}"
            VARS["$prompt_var"]="${raw/#\~/$HOME}"
        elif [[ -n "$prompt_var" ]]; then
            VARS["$prompt_var"]="${VARS[$prompt_var]/#\~/$HOME}"
        fi

        check="$(substitute_vars "$check")"
        action="$(substitute_vars "$action")"

        if eval "$check" &>/dev/null; then
            skip "${name} (already done)"
        else
            run_msg "${name}"
            if ! eval "$action"; then
                fail "${name}"
                return 1
            fi
        fi
    done
}

# ─── Phase: Configuration Wizard ────────────────────────────────────────────

apply_manifest_defaults() {
    local count i key default_val
    count="$(manifest_len ".config.prompts")"
    for (( i=0; i<count; i++ )); do
        key="$(manifest_get ".config.prompts[$i].key")"
        default_val="$(manifest_get ".config.prompts[$i].default")"
        if [[ -n "$key" ]]; then
            VARS["$key"]="${default_val:-}"
        fi
    done
    count="$(manifest_len ".setup_steps")"
    for (( i=0; i<count; i++ )); do
        key="$(manifest_get ".setup_steps[$i].prompt_var")"
        default_val="$(manifest_get ".setup_steps[$i].default")"
        if [[ -n "$key" && -z "${VARS[$key]+_}" ]]; then
            VARS["$key"]="${default_val/#\~/$HOME}"
        fi
    done
    expand_path_vars
}

fill_missing_from_manifest() {
    local count i key default_val
    count="$(manifest_len ".config.prompts")"
    for (( i=0; i<count; i++ )); do
        key="$(manifest_get ".config.prompts[$i].key")"
        default_val="$(manifest_get ".config.prompts[$i].default")"
        if [[ -n "$key" && -z "${VARS[$key]+_}" ]]; then
            VARS["$key"]="${default_val:-}"
        fi
    done
    count="$(manifest_len ".setup_steps")"
    for (( i=0; i<count; i++ )); do
        key="$(manifest_get ".setup_steps[$i].prompt_var")"
        default_val="$(manifest_get ".setup_steps[$i].default")"
        if [[ -n "$key" && -z "${VARS[$key]+_}" ]]; then
            VARS["$key"]="${default_val/#\~/$HOME}"
        fi
    done
    expand_path_vars
}

show_config_summary() {
    local secrets_path secrets_st pull_st agd_st
    secrets_path="$(secrets_file_path)"
    secrets_st="$(secrets_status)"
    case "$secrets_st" in
        missing)      secrets_st="MISSING" ;;
        placeholders) secrets_st="PLACEHOLDERS (needs edit)" ;;
        ok)           secrets_st="OK" ;;
    esac

    if [[ -n "${VARS[pull_secret_path]:-}" && -f "${VARS[pull_secret_path]}" ]]; then
        pull_st="OK"
    else
        pull_st="MISSING"
    fi

    if [[ -n "${VARS[agnosticd_root]:-}" && -x "${VARS[agnosticd_root]}/bin/agd" ]]; then
        agd_st="OK"
    else
        agd_st="MISSING"
    fi

    echo ""
    echo -e "${BOLD}--- Configuration Summary ---${RESET}"
    echo ""
    echo "  account:          ${VARS[account]:-}"
    echo "  aws_region:       ${VARS[aws_region]:-}"
    echo "  base_domain:      ${VARS[base_domain]:-}"
    echo "  owner:            ${VARS[owner]:-}"
    echo "  num_students:     ${VARS[num_students]:-}"
    echo "  deploy_hub:       ${VARS[deploy_hub]:-}"
    echo "  hub_guid:         ${VARS[hub_guid]:-}"
    echo "  parallel:         ${VARS[parallel]:-}"
    echo "  agnosticd_root:   ${VARS[agnosticd_root]:-}  [${agd_st}]"
    echo "  pull_secret_path: ${VARS[pull_secret_path]:-}  [${pull_st}]"
    echo "  secrets_file:     ${secrets_path:-?}  [${secrets_st}]"
    echo ""
}

prompt_all_config() {
    local count i key prompt_text default_val required choices choices_str current
    count="$(manifest_len ".config.prompts")"
    for (( i=0; i<count; i++ )); do
        key="$(manifest_get ".config.prompts[$i].key")"
        prompt_text="$(manifest_get ".config.prompts[$i].prompt")"
        default_val="$(manifest_get ".config.prompts[$i].default")"
        required="$(manifest_get ".config.prompts[$i].required")"
        choices="$(manifest_get ".config.prompts[$i].choices")"
        choices_str="$(choices_to_str "$choices")"
        current="${VARS[$key]:-$default_val}"
        prompt_for "$key" "$prompt_text" "$current" "$choices_str" "${required:-false}"
    done
    expand_path_vars
}

save_config() {
    local count i key output_file gitignore
    count="$(manifest_len ".config.prompts")"
    (( count == 0 )) && return 0

    expand_path_vars
    output_file="$(manifest_get ".config.output_file")"
    [[ -z "$output_file" ]] && return 0

    mkdir -p "$(dirname "$output_file")"
    {
        echo "# Generated by bootstrap.sh — re-run to reconfigure"
        echo "# DO NOT commit this file (contains environment-specific values)"
        for (( i=0; i<count; i++ )); do
            key="$(manifest_get ".config.prompts[$i].key")"
            echo "${key}: ${VARS[$key]:-}"
        done
    } > "$output_file"
    info "Config saved to: ${output_file}"

    gitignore="$(manifest_get ".config.gitignore")"
    if [[ "$gitignore" == "true" ]]; then
        if ! grep -qF "$output_file" .gitignore 2>/dev/null; then
            echo "$output_file" >> .gitignore
            info "Added ${output_file} to .gitignore"
        fi
    fi
}

configure() {
    local count
    count="$(manifest_len ".config.prompts")"
    if (( count == 0 )); then return 0; fi

    fill_missing_from_manifest
    show_config_summary

    if [[ "$NON_INTERACTIVE" == "true" ]]; then
        save_config
        return 0
    fi

    local choice
    if [[ "$CONFIG_FROM_FILE" == "true" ]]; then
        echo "  [k] Keep existing values"
        echo "  [e] Edit values (Enter accepts current)"
        echo "  [r] Reset to manifest defaults and edit"
        read -rp "  Choice [k/e/r] (default: k): " choice
        choice="${choice:-k}"
    else
        echo "  No saved config yet. Review defaults below, then edit or accept."
        echo "  [e] Edit values (Enter accepts shown default)"
        echo "  [k] Keep defaults as-is"
        echo "  [r] Reset to manifest defaults and edit"
        read -rp "  Choice [e/k/r] (default: e): " choice
        choice="${choice:-e}"
    fi

    case "$choice" in
        k|K)
            info "Keeping current configuration."
            ;;
        r|R)
            info "Resetting to manifest defaults..."
            VARS=()
            CONFIG_FROM_FILE=false
            apply_manifest_defaults
            echo ""
            echo -e "${BOLD}--- Edit Configuration ---${RESET}"
            echo ""
            prompt_all_config
            ;;
        e|E|*)
            echo ""
            echo -e "${BOLD}--- Edit Configuration ---${RESET}"
            echo ""
            prompt_all_config
            ;;
    esac

    show_config_summary
    save_config
}

# ─── Phase: Secrets Assist ──────────────────────────────────────────────────

assist_pull_secret() {
    local secrets_yml pull_path result
    secrets_yml="${VARS[agnosticd_root]:-}/../agnosticd-v2-secrets/secrets.yml"
    pull_path="${VARS[pull_secret_path]:-}"

    if [[ -z "$pull_path" || ! -f "$pull_path" ]]; then
        warn_msg "Pull secret file missing (${pull_path:-unset}). Download from console.redhat.com."
        return 0
    fi

    if [[ ! -f "$secrets_yml" ]]; then
        warn_msg "AgnosticD secrets.yml not found: ${secrets_yml}"
        return 0
    fi

    # Always sync pull-secret.json → secrets.yml during setup (idempotent).
    if ! result="$(python3 -c "
import json, sys, yaml

pull_path, secrets_yml = sys.argv[1], sys.argv[2]
try:
    ps = json.load(open(pull_path))
except Exception as e:
    print(f'ERROR: {pull_path} is not valid JSON: {e}', file=sys.stderr)
    sys.exit(2)
if not isinstance(ps, dict) or 'auths' not in ps:
    print(f'ERROR: {pull_path} is not an OpenShift pull secret (missing auths)', file=sys.stderr)
    sys.exit(2)

new_val = json.dumps(ps)
d = yaml.safe_load(open(secrets_yml)) or {}
old = d.get('ocp4_pull_secret') or ''
if old == new_val:
    print('unchanged')
    sys.exit(0)
d['ocp4_pull_secret'] = new_val
with open(secrets_yml, 'w') as f:
    yaml.safe_dump(d, f, default_flow_style=False, sort_keys=False)
print('updated')
" "$pull_path" "$secrets_yml")"; then
        fail "Failed to sync ocp4_pull_secret from ${pull_path}"
        return 1
    fi

    if [[ "$result" == "unchanged" ]]; then
        ok "ocp4_pull_secret already matches ${pull_path}"
    else
        ok "ocp4_pull_secret updated in secrets.yml from ${pull_path}"
    fi
}

# Returns 0 if value looks like a real LINBIT registry credential (not a placeholder).
_linbit_cred_is_real() {
    python3 -c "
import sys
v = (sys.argv[1] or '').strip()
if not v:
    sys.exit(1)
low = v.lower()
if v.startswith('<') or v.endswith('>'):
    sys.exit(1)
if 'your linbit' in low or 'change_me' in low or 'changeme' in low:
    sys.exit(1)
if low in ('xxx', 'xxxx', 'todo', 'example', 'placeholder', 'your-portal-email', 'your-portal-password'):
    sys.exit(1)
sys.exit(0)
" "$1"
}

_write_linbit_registry_secrets() {
    local secrets_yml user pass
    secrets_yml="$1"
    user="$2"
    pass="$3"
    python3 -c "
import sys, yaml
path, user, password = sys.argv[1], sys.argv[2], sys.argv[3]
d = yaml.safe_load(open(path)) or {}
d['linbit_registry_username'] = user
d['linbit_registry_password'] = password
with open(path, 'w') as f:
    yaml.safe_dump(d, f, default_flow_style=False, sort_keys=False)
" "$secrets_yml" "$user" "$pass"
}

assist_linbit_registry() {
    local secrets_yml user pass reply cur_user cur_pass
    secrets_yml="${VARS[agnosticd_root]:-}/../agnosticd-v2-secrets/secrets.yml"
    secrets_yml="${secrets_yml/#\~/$HOME}"

    echo ""
    info "LINBIT Customer Portal credentials (drbd.io pull secret)"
    echo "      Portal: https://my.linbit.com/"
    echo "      How-to: docs/setup/linbit-registry-credentials.md"
    echo "      Written to: ${secrets_yml}"

    if [[ ! -f "$secrets_yml" ]]; then
        warn_msg "AgnosticD secrets.yml not found: ${secrets_yml}"
        return 0
    fi

    cur_user="$(python3 -c "import yaml,sys; d=yaml.safe_load(open(sys.argv[1])) or {}; print((d.get('linbit_registry_username') or '').strip())" "$secrets_yml")"
    cur_pass="$(python3 -c "import yaml,sys; d=yaml.safe_load(open(sys.argv[1])) or {}; print((d.get('linbit_registry_password') or '').strip())" "$secrets_yml")"

    if _linbit_cred_is_real "$cur_user" && _linbit_cred_is_real "$cur_pass"; then
        ok "LINBIT registry credentials already set in secrets.yml (user: ${cur_user})"
        if [[ "$NON_INTERACTIVE" == "true" ]]; then
            return 0
        fi
        read -rp "  Keep existing LINBIT credentials? [Y/n]: " reply
        reply="${reply:-Y}"
        if [[ "$reply" =~ ^[Yy]$ ]]; then
            return 0
        fi
    else
        warn_msg "LINBIT registry credentials missing or still placeholders in secrets.yml"
        if [[ "$NON_INTERACTIVE" == "true" ]]; then
            warn_msg "Non-interactive mode: edit secrets.yml or re-run make setup interactively."
            return 0
        fi
    fi

    echo "      Enter your my.linbit.com email and password (used for drbd.io image pulls)."
    read -rp "  LINBIT portal email: " user
    user="$(echo "$user" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    if ! _linbit_cred_is_real "$user"; then
        read -rp "  Email looks empty/placeholder. Re-enter LINBIT portal email: " user
        user="$(echo "$user" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    fi
    if ! _linbit_cred_is_real "$user"; then
        warn_msg "Skipping LINBIT write — username still empty or placeholder."
        return 0
    fi

    read -rsp "  LINBIT portal password: " pass
    echo ""
    pass="$(echo "$pass" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    if ! _linbit_cred_is_real "$pass"; then
        read -rsp "  Password looks empty/placeholder. Re-enter LINBIT portal password: " pass
        echo ""
        pass="$(echo "$pass" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    fi
    if ! _linbit_cred_is_real "$pass"; then
        warn_msg "Skipping LINBIT write — password still empty or placeholder."
        return 0
    fi

    if _write_linbit_registry_secrets "$secrets_yml" "$user" "$pass"; then
        ok "linbit_registry_* written to ${secrets_yml}"
    else
        fail "Failed to write LINBIT credentials to ${secrets_yml}"
        return 1
    fi
}

assist_secrets() {
    local path status editor reply
    path="$(secrets_file_path)"

    echo ""
    echo -e "${BOLD}--- Secrets ---${RESET}"
    echo ""

    assist_pull_secret
    assist_linbit_registry

    if [[ -z "$path" ]]; then
        warn_msg "Cannot resolve account secrets path (account / agnosticd_root unset)."
        return 0
    fi

    status="$(secrets_status)"
    case "$status" in
        missing)
            warn_msg "Secrets file not found: ${path}"
            echo "      Create it from the AgnosticD template, then fill in AWS credentials."
            ;;
        placeholders)
            # Auto-fix: if AWS CLI is configured, populate credentials automatically
            local ak sk
            ak="$(aws configure get aws_access_key_id 2>/dev/null || true)"
            sk="$(aws configure get aws_secret_access_key 2>/dev/null || true)"
            if [[ -n "$ak" && -n "$sk" ]]; then
                printf '%s\n' "---" "aws_access_key_id: ${ak}" "aws_secret_access_key: ${sk}" \
                    "base_domain: ${VARS[base_domain]:-}" \
                    "agnosticd_aws_capacity_reservation_enable: false" > "$path"
                ok "Auto-populated secrets-${VARS[account]}.yml from AWS CLI credentials."
                return 0
            fi
            warn_msg "Secrets file has placeholder values: ${path}"
            echo "      Edit the file and replace <Your ...> placeholders with real credentials."
            ;;
        ok)
            ok "Account secrets file looks configured: ${path}"
            return 0
            ;;
    esac

    if [[ "$NON_INTERACTIVE" == "true" ]]; then
        return 0
    fi

    if [[ ! -f "$path" ]]; then
        return 0
    fi

    editor="${EDITOR:-vi}"
    read -rp "  Open account secrets file in ${editor}? [Y/n]: " reply
    reply="${reply:-Y}"
    if [[ "$reply" =~ ^[Yy]$ ]]; then
        "$editor" "$path" || true
        status="$(secrets_status)"
        if [[ "$status" == "ok" ]]; then
            ok "Secrets file updated."
        else
            warn_msg "Secrets file may still need credentials before deploy."
        fi
    fi
}

# ─── Phase: Validation + Readiness Gate ──────────────────────────────────────

validate() {
    local count
    count="$(manifest_len ".validation")"

    echo ""
    echo -e "${BOLD}--- Validation ---${RESET}"
    echo ""

    local required_total=0 required_passed=0 warnings=0

    local i name command required_flag fail_message
    for (( i=0; i<count; i++ )); do
        name="$(manifest_get ".validation[$i].name")"
        command="$(manifest_get ".validation[$i].command")"
        required_flag="$(manifest_get ".validation[$i].required")"
        fail_message="$(manifest_get ".validation[$i].fail_message")"

        command="$(substitute_vars "$command")"
        fail_message="$(substitute_vars "$fail_message")"

        if [[ "$required_flag" == "true" ]]; then
            required_total=$((required_total + 1))
        fi

        local cmd_output cmd_rc
        cmd_output=$(eval "$command" 2>&1) && cmd_rc=0 || cmd_rc=$?

        if (( cmd_rc == 0 )); then
            pass "${name}"
            if [[ "$required_flag" == "true" ]]; then
                required_passed=$((required_passed + 1))
            fi
        else
            if [[ "$required_flag" == "true" ]]; then
                fail "${name} (exit $cmd_rc)"
            else
                warn_msg "${name}"
                warnings=$((warnings + 1))
            fi
            [[ -n "$fail_message" ]] && echo "      ${fail_message}"
            [[ -n "$cmd_output" ]] && echo "      Output: ${cmd_output:0:200}"
        fi
    done

    echo ""
    if (( required_total == 0 )); then
        info "No required checks defined. ${warnings} warning(s)."
        return 0
    fi

    if (( required_passed == required_total )); then
        info "Readiness: ${required_passed}/${required_total} required checks passed (${warnings} warning(s)). Ready to deploy!"
        return 0
    else
        local failed=$((required_total - required_passed))
        fail "Readiness: ${required_passed}/${required_total} required checks passed (${warnings} warning(s))"
        fail "BLOCKED: ${failed} required check(s) failed. Fix the issues above before deploying."
        return 1
    fi
}

# ─── Phase: Quota Checks ────────────────────────────────────────────────────

run_quota_checks() {
    local count
    count="$(manifest_len ".quota_checks")"
    if (( count == 0 )); then return 0; fi

    echo ""
    echo -e "${BOLD}--- Quota Check ---${RESET}"
    info "Sizing for num_students=${VARS[num_students]:-2} (hub + student clusters)"
    echo ""

    local total=0 passed=0
    local i label needed needed_expr limit_cmd usage_cmd fail_message
    for (( i=0; i<count; i++ )); do
        label="$(manifest_get ".quota_checks[$i].label")"
        needed_expr="$(manifest_get ".quota_checks[$i].needed")"
        limit_cmd="$(manifest_get ".quota_checks[$i].limit_command")"
        usage_cmd="$(manifest_get ".quota_checks[$i].usage_command")"
        fail_message="$(manifest_get ".quota_checks[$i].fail_message")"

        needed_expr="$(substitute_vars "$needed_expr")"
        limit_cmd="$(substitute_vars "$limit_cmd")"
        usage_cmd="$(substitute_vars "$usage_cmd")"
        fail_message="$(substitute_vars "$fail_message")"

        # Support plain integers or arithmetic expressions (e.g. 30 + 22 * 2)
        if [[ "$needed_expr" =~ ^[0-9+\*/%().[:space:]-]+$ ]]; then
            needed=$((needed_expr))
        else
            needed=0
        fi

        total=$((total + 1))

        local limit_val usage_val available
        limit_val=$(eval "$limit_cmd" 2>/dev/null | tr -d '[:space:]' || true)
        usage_val=$(eval "$usage_cmd" 2>/dev/null | tr -d '[:space:]' || true)

        # AWS --output text may return "None"; keep only a numeric value.
        limit_val="${limit_val%%.*}"
        usage_val="${usage_val%%.*}"
        [[ "$limit_val" =~ ^-?[0-9]+$ ]] || limit_val=0
        [[ "$usage_val" =~ ^-?[0-9]+$ ]] || usage_val=0

        available=$((limit_val - usage_val))

        if (( available >= needed )); then
            pass "${label}: need ${needed}, available ${available} (limit: ${limit_val}, used: ${usage_val})"
            passed=$((passed + 1))
        else
            fail "${label}: need ${needed}, available ${available} (limit: ${limit_val}, used: ${usage_val})"
            [[ -n "$fail_message" ]] && echo "      ${fail_message}"
        fi
    done

    echo ""
    if (( passed == total )); then
        info "Quota: ${passed}/${total} checks passed. Sufficient capacity."
        return 0
    else
        local failed=$((total - passed))
        fail "Quota: ${passed}/${total} checks passed"
        fail "BLOCKED: Insufficient quota. Run: make request-quotas"
        return 1
    fi
}

# ─── Phase: Post-Setup ──────────────────────────────────────────────────────

show_post_setup() {
    local message
    message="$(manifest_get ".post_setup.message")"
    if [[ -z "$message" ]]; then return; fi

    echo ""
    echo -e "${BOLD}--- Next Steps ---${RESET}"
    echo ""
    substitute_vars "$message"
}

# ─── Load Defaults (config.yml or manifest) ──────────────────────────────────

load_defaults() {
    local config_file line key value
    config_file="$(manifest_get ".config.output_file")"
    CONFIG_FROM_FILE=false

    if [[ -n "$config_file" && -f "$config_file" ]]; then
        while IFS= read -r line || [[ -n "$line" ]]; do
            [[ "$line" =~ ^[[:space:]]*# ]] && continue
            [[ -z "${line// /}" ]] && continue
            key="${line%%:*}"
            value="${line#*:}"
            key="${key#"${key%%[![:space:]]*}"}"
            key="${key%"${key##*[![:space:]]}"}"
            value="${value#"${value%%[![:space:]]*}"}"
            value="${value%"${value##*[![:space:]]}"}"
            value="${value#\"}"
            value="${value%\"}"
            value="${value#\'}"
            value="${value%\'}"
            [[ -z "$key" ]] && continue
            VARS["$key"]="$value"
        done < "$config_file"
        expand_path_vars
        fill_missing_from_manifest
        CONFIG_FROM_FILE=true
        info "Loaded config from: ${config_file}"
        return
    fi

    apply_manifest_defaults
    info "Using manifest defaults (no config file found)"
}

# ─── Main ────────────────────────────────────────────────────────────────────

main() {
    local project_name project_desc
    project_name="$(manifest_get ".name")"
    project_desc="$(manifest_get ".description")"

    echo ""
    echo -e "${BOLD}=== ${project_name} Setup (${MODE} mode) ===${RESET}"
    [[ -n "$project_desc" ]] && echo "$project_desc"
    echo ""

    local distro
    distro="$(detect_distro)"
    info "Detected platform: ${distro}"
    info "Manifest: ${MANIFEST}"

    load_defaults

    if [[ "$CHECK_ONLY" == "true" ]]; then
        show_config_summary
        local rc=0
        validate || rc=1
        run_quota_checks || rc=1
        show_post_setup
        exit $rc
    fi

    install_prerequisites "$distro" ".prerequisites" "Prerequisites"

    if [[ "$MODE" == "dev" ]]; then
        local dev_extras_count
        dev_extras_count="$(manifest_len ".modes.dev.extra_prerequisites")"
        if (( dev_extras_count > 0 )); then
            install_prerequisites "$distro" ".modes.dev.extra_prerequisites" "Dev Prerequisites"
        fi
    fi

    # Config first so ${account} / paths are available for setup + secrets
    configure
    run_setup_steps
    assist_secrets

    local validation_passed=true
    if ! validate; then
        validation_passed=false
    fi

    local quota_passed=true
    if ! run_quota_checks; then
        quota_passed=false
    fi

    show_post_setup

    if [[ "$MODE" == "prod" && "$validation_passed" == "true" && "$quota_passed" == "true" ]]; then
        local deploy_cmd
        deploy_cmd="$(manifest_get ".modes.prod.post_validation_command")"
        if [[ -n "$deploy_cmd" ]]; then
            deploy_cmd="$(substitute_vars "$deploy_cmd")"
            echo ""
            if [[ "$NON_INTERACTIVE" == "true" ]]; then
                info "Running: ${deploy_cmd}"
                eval "$deploy_cmd"
            else
                local deploy_reply
                read -rp "  Deploy now? [y/N]: " deploy_reply
                if [[ "$deploy_reply" =~ ^[Yy]$ ]]; then
                    echo ""
                    echo -e "${BOLD}--- Deploying ---${RESET}"
                    echo ""
                    info "Running: ${deploy_cmd}"
                    eval "$deploy_cmd"
                else
                    info "Skipping deploy. Run later with: make deploy"
                fi
            fi
        fi
    elif [[ "$MODE" == "prod" && ("$validation_passed" == "false" || "$quota_passed" == "false") ]]; then
        echo ""
        fail "Deployment skipped — resolve all failures above first."
        exit 1
    fi
}

main
