---
site:
  title: LINBIT Edge Storage Workshop
  url: https://tosin2013.github.io/openshift-tnf-edge-storage
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/latest/ui-bundle.zip
    snapshot: true

output:
  dir: ./www
