---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.%openshift_cluster_ingress_domain%'

  - name: Terminal
    path: /wetty
    port: 443
