apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.rwoLocality.name }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
  {{- if .Values.rwoLocality.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
  {{- end }}
provisioner: linstor.csi.linbit.com
parameters:
  autoPlace: "{{ .Values.rwoLocality.replicaCount }}"
  storagePool: {{ .Values.rwoLocality.storagePool }}
  csi.storage.k8s.io/fstype: {{ .Values.rwoLocality.fsType }}
  {{- if .Values.rwoLocality.quorum }}
  property.linstor.csi.linbit.com/DrbdOptions/auto-quorum: {{ .Values.rwoLocality.quorum | quote }}
  property.linstor.csi.linbit.com/DrbdOptions/Resource/on-no-quorum: {{ .Values.rwoLocality.onNoQuorum | quote }}
  {{- end }}
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.rwxVirt.name }}
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
provisioner: linstor.csi.linbit.com
parameters:
  autoPlace: "{{ .Values.rwxVirt.replicaCount }}"
  storagePool: {{ .Values.rwxVirt.storagePool }}
  {{- if .Values.rwxVirt.allowTwoPrimaries }}
  property.linstor.csi.linbit.com/DrbdOptions/Net/allow-two-primaries: "yes"
  {{- end }}
  {{- if .Values.rwxVirt.quorum }}
  property.linstor.csi.linbit.com/DrbdOptions/auto-quorum: {{ .Values.rwxVirt.quorum | quote }}
  property.linstor.csi.linbit.com/DrbdOptions/Resource/on-no-quorum: {{ .Values.rwxVirt.onNoQuorum | quote }}
  {{- end }}
volumeBindingMode: Immediate
reclaimPolicy: Delete
allowVolumeExpansion: true
