#!/usr/bin/env bash
# ===================================================================
# LINBIT Edge Storage Workshop — Full Deployment
# Deploys a hub cluster (RHACM + Showroom) then N student TNA clusters,
# each auto-imported into hub RHACM.
#
# Prerequisites:
#   - Run: make setup (or ./bootstrap.sh) to install prereqs and configure
#   - agnosticd-v2 cloned and agd setup completed
#   - secrets-<ACCOUNT>.yml filled in with AWS credentials
#   - Pull secret at the configured path
#
# Usage:
#   ./agnosticd/deploy.sh                       # use config.yml defaults
#   NUM_STUDENTS=4 ./agnosticd/deploy.sh        # override student count
#   DEPLOY_HUB=false ./agnosticd/deploy.sh      # students only (hub exists)
#   PARALLEL=true ./agnosticd/deploy.sh          # deploy students in parallel
# ===================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# -----------------------------------------------------------------
# Read config.yml (generated by onboard / bootstrap.sh)
# Environment variables take precedence over config file values.
# -----------------------------------------------------------------
CONFIG_FILE="${SCRIPT_DIR}/config.yml"
if [[ -f "$CONFIG_FILE" ]]; then
  while IFS=': ' read -r key value; do
    key=$(echo "$key" | tr -d ' ')
    value=$(echo "$value" | tr -d '"' | tr -d "'")
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    upper_key=$(echo "$key" | tr '[:lower:]' '[:upper:]')
    if [[ -z "${!upper_key:-}" ]]; then
      export "$upper_key=$value"
    fi
  done < "$CONFIG_FILE"
fi

# Map config keys to script variables (env vars override config, config overrides defaults)
AGNOSTICD_ROOT="${AGNOSTICD_ROOT:-${AGNOSTICD_ROOT_CONFIG:-$HOME/Development/agnosticd-v2}}"
AGNOSTICD_ROOT="${AGNOSTICD_ROOT/#\~/$HOME}"
AGNOSTICD_VARS="${AGNOSTICD_ROOT}/../agnosticd-v2-vars"
ACCOUNT="${ACCOUNT:-${ACCOUNT_CONFIG:-sandbox2530}}"

DEPLOY_HUB="${DEPLOY_HUB:-true}"
HUB_GUID="${HUB_GUID:-linbit-hub}"
HUB_CONFIG_NAME="linbit-hub"

BASE_GUID="${BASE_GUID:-linbit}"
STUDENT_CONFIG_NAME="linbit-student"
NUM_STUDENTS="${NUM_STUDENTS:-2}"
PARALLEL="${PARALLEL:-false}"

STATE_DIR="${SCRIPT_DIR}/.state"
MANIFEST="${STATE_DIR}/students.txt"

mkdir -p "$STATE_DIR"

# -----------------------------------------------------------------
# Fail-fast prerequisite checks
# -----------------------------------------------------------------
for cmd in podman oc jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: $cmd is required but not found. Run: make setup"
    exit 1
  fi
done

if [[ ! -d "$AGNOSTICD_ROOT" ]]; then
  echo "ERROR: AgnosticD v2 not found at $AGNOSTICD_ROOT"
  echo "Clone it: git clone https://github.com/tosin2013/agnosticd-v2.git $AGNOSTICD_ROOT"
  exit 1
fi

if [[ ! -f "$AGNOSTICD_ROOT/bin/agd" ]]; then
  echo "ERROR: agd CLI not found. Run: cd $AGNOSTICD_ROOT && ./bin/agd setup"
  exit 1
fi

# -----------------------------------------------------------------
# Copy vars files into agnosticd-v2-vars/ (agd expects them there)
# Copy, not symlink — symlinks break inside containers (see deploy-hardening.md)
# -----------------------------------------------------------------
echo "Copying vars files into $AGNOSTICD_VARS ..."
mkdir -p "$AGNOSTICD_VARS"
cp "$SCRIPT_DIR/vars/hub/linbit-hub.yaml" "$AGNOSTICD_VARS/${HUB_CONFIG_NAME}.yml"
cp "$SCRIPT_DIR/vars/student/linbit-student.yaml" "$AGNOSTICD_VARS/${STUDENT_CONFIG_NAME}.yml"

cd "$AGNOSTICD_ROOT"

# -----------------------------------------------------------------
# Phase 1: Deploy hub cluster
# -----------------------------------------------------------------
if [[ "$DEPLOY_HUB" == "true" ]]; then
  echo "============================================================"
  echo "Phase 1: Deploying hub cluster ($HUB_GUID)"
  echo "  Config: openshift-cluster (HA: 3 CP + 2 Workers)"
  echo "  Workloads: cert-manager, auth, RHACM, Showroom"
  echo "============================================================"
  ./bin/agd provision \
    -g "$HUB_GUID" \
    -c "$HUB_CONFIG_NAME" \
    -a "$ACCOUNT"

  echo ""
  echo "Hub cluster deployed successfully."
fi

# -----------------------------------------------------------------
# Phase 2: Extract hub API URL and create a service-account token
# -----------------------------------------------------------------
echo "============================================================"
echo "Phase 2: Extracting hub credentials for RHACM import"
echo "============================================================"

HUB_OUTPUT="${AGNOSTICD_ROOT}/../agnosticd-v2-output/${HUB_GUID}"

KUBECONFIG_PATH=""
for candidate in \
  "${HUB_OUTPUT}/kubeconfig" \
  "${HUB_OUTPUT}/ocp4-cluster/auth/kubeconfig" \
  "${HUB_OUTPUT}/auth/kubeconfig"; do
  if [[ -f "$candidate" ]]; then
    KUBECONFIG_PATH="$candidate"
    break
  fi
done

if [[ -z "$KUBECONFIG_PATH" ]]; then
  echo "ERROR: Hub kubeconfig not found under $HUB_OUTPUT"
  echo "Ensure the hub cluster ($HUB_GUID) is deployed."
  exit 1
fi

export KUBECONFIG="$KUBECONFIG_PATH"
echo "Using kubeconfig: $KUBECONFIG_PATH"

HUB_API_URL=$(oc whoami --show-server 2>/dev/null)
echo "Hub API: $HUB_API_URL"

echo "Waiting for hub API..."
for i in $(seq 1 30); do
  if oc get nodes &>/dev/null; then
    echo "Hub cluster API is reachable."
    break
  fi
  sleep 10
done

oc get namespace rhacm-import-sa 2>/dev/null || \
  oc create namespace rhacm-import-sa

oc get sa rhacm-import -n rhacm-import-sa 2>/dev/null || \
  oc create sa rhacm-import -n rhacm-import-sa

oc get clusterrolebinding rhacm-import-binding 2>/dev/null || \
  oc create clusterrolebinding rhacm-import-binding \
    --clusterrole=cluster-admin \
    --serviceaccount=rhacm-import-sa:rhacm-import

HUB_TOKEN=$(oc create token rhacm-import -n rhacm-import-sa --duration=24h)

echo "Hub token extracted (24h TTL)."
echo "$HUB_API_URL" > "$STATE_DIR/hub_api_url"
echo "$HUB_TOKEN"   > "$STATE_DIR/hub_token"

unset KUBECONFIG

# -----------------------------------------------------------------
# Phase 3: Deploy student clusters with hub credentials injected
# -----------------------------------------------------------------
echo "============================================================"
echo "Phase 3: Deploying $NUM_STUDENTS student cluster(s)"
echo "  Topology: TNA (2 primary + 1 arbiter)"
echo "  Workloads: cert-manager, LINBIT SDS (field-content), RHACM import"
echo "============================================================"

STUDENT_VARS_SRC="$SCRIPT_DIR/vars/student/linbit-student.yaml"

sed_inplace() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

inject_hub_credentials() {
  local student_num="$1"
  local guid="${BASE_GUID}-s${student_num}"
  local student_vars_file="${AGNOSTICD_VARS}/linbit-student-${student_num}.yml"

  cp "$STUDENT_VARS_SRC" "$student_vars_file"

  sed_inplace "s|^ocp4_workload_rhacm_import_hub_api_url:.*|ocp4_workload_rhacm_import_hub_api_url: \"${HUB_API_URL}\"|" "$student_vars_file"
  sed_inplace "s|^ocp4_workload_rhacm_import_hub_token:.*|ocp4_workload_rhacm_import_hub_token: \"${HUB_TOKEN}\"|" "$student_vars_file"
  sed_inplace "s|^ocp4_workload_rhacm_import_student_cluster_name:.*|ocp4_workload_rhacm_import_student_cluster_name: \"${guid}\"|" "$student_vars_file"

  echo "$student_vars_file"
}

> "$MANIFEST"

deploy_student() {
  local student_num="$1"
  local guid="${BASE_GUID}-s${student_num}"
  local config_name="linbit-student-${student_num}"

  echo "$guid" >> "$MANIFEST"
  echo "==> Deploying student cluster ($guid) ..."

  inject_hub_credentials "$student_num" > /dev/null

  ./bin/agd provision \
    -g "$guid" \
    -c "$config_name" \
    -a "$ACCOUNT"

  echo "==> Student cluster ($guid) deployed and imported into RHACM."
}

if [[ "$PARALLEL" == "true" ]]; then
  for i in $(seq 1 "$NUM_STUDENTS"); do
    inject_hub_credentials "$i" > /dev/null
  done
  pids=()
  for i in $(seq 1 "$NUM_STUDENTS"); do
    deploy_student "$i" &
    pids+=($!)
  done
  echo "Waiting for $NUM_STUDENTS parallel deployments..."
  failed=0
  for pid in "${pids[@]}"; do
    if ! wait "$pid"; then
      echo "ERROR: Process $pid failed"
      failed=$((failed + 1))
    fi
  done
  if (( failed > 0 )); then
    echo "ERROR: $failed/$NUM_STUDENTS student provisioning(s) failed."
    exit 1
  fi
else
  for i in $(seq 1 "$NUM_STUDENTS"); do
    deploy_student "$i"
  done
fi

# -----------------------------------------------------------------
# Summary
# -----------------------------------------------------------------
echo ""
echo "============================================================"
echo "Deployment Complete"
echo "============================================================"
echo "Hub cluster:      $HUB_GUID"
echo "Hub API:          $HUB_API_URL"
echo "Student clusters: $NUM_STUDENTS"
echo ""
cat "$MANIFEST"
echo ""
echo "Showroom: Check hub cluster routes for Showroom URL"
echo "RHACM:   KUBECONFIG=$KUBECONFIG_PATH oc get managedclusters"
