#!/usr/bin/env bash
# ===================================================================
# LINBIT Edge Storage Workshop — Full Deployment
# Deploys a hub cluster (RHACM + Showroom) then N student TNA clusters,
# each auto-imported into hub RHACM.
#
# Prerequisites:
#   - Run: make setup (or ./bootstrap.sh) to install prereqs and configure
#   - agnosticd-v2 cloned and agd setup completed
#   - secrets-<ACCOUNT>.yml filled in with AWS credentials
#   - Pull secret at the configured path
#   - Real linbit_registry_username / linbit_registry_password in
#     agnosticd-v2-secrets/secrets.yml (placeholders hard-fail this script)
#
# Usage:
#   ./agnosticd/deploy.sh                       # use config.yml defaults
#   NUM_STUDENTS=4 ./agnosticd/deploy.sh        # override student count
#   DEPLOY_HUB=false ./agnosticd/deploy.sh      # students only (hub exists)
#   PARALLEL=true ./agnosticd/deploy.sh         # deploy students in parallel
#   YES=true ./agnosticd/deploy.sh              # non-interactive confirm
#   ./agnosticd/deploy.sh --yes                 # same
#   make deploy ARGS=--yes
# ===================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOCK_FILE="${SCRIPT_DIR}/.workshop-lock"

# -----------------------------------------------------------------
# Read config.yml (generated by onboard / bootstrap.sh)
# Environment variables take precedence over config file values.
# -----------------------------------------------------------------
CONFIG_FILE="${SCRIPT_DIR}/config.yml"
if [[ -f "$CONFIG_FILE" ]]; then
  while IFS=': ' read -r key value; do
    key=$(echo "$key" | tr -d ' ')
    value=$(echo "$value" | tr -d '"' | tr -d "'")
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    upper_key=$(echo "$key" | tr '[:lower:]' '[:upper:]')
    if [[ -z "${!upper_key:-}" ]]; then
      export "$upper_key=$value"
    fi
  done < "$CONFIG_FILE"
fi

# Map config keys to script variables (env vars override config, config overrides defaults)
AGNOSTICD_ROOT="${AGNOSTICD_ROOT:-${AGNOSTICD_ROOT_CONFIG:-$HOME/Development/agnosticd-v2}}"
AGNOSTICD_ROOT="${AGNOSTICD_ROOT/#\~/$HOME}"
AGNOSTICD_VARS="${AGNOSTICD_ROOT}/../agnosticd-v2-vars"
ACCOUNT="${ACCOUNT:-${ACCOUNT_CONFIG:-sandbox2530}}"

DEPLOY_HUB="${DEPLOY_HUB:-true}"
HUB_GUID="${HUB_GUID:-linbit-hub}"
HUB_CONFIG_NAME="linbit-hub"

BASE_GUID="${BASE_GUID:-linbit}"
STUDENT_CONFIG_NAME="linbit-student"
NUM_STUDENTS="${NUM_STUDENTS:-2}"
PARALLEL="${PARALLEL:-false}"
YES="${YES:-false}"

# Student deploy method: "agent-based" (true TNA) or "ipi" (legacy 6-node via AgnosticD)
STUDENT_DEPLOY_METHOD="${STUDENT_DEPLOY_METHOD:-agent-based}"

# CLI flags
for arg in "$@"; do
  case "$arg" in
    --yes|-y) YES=true ;;
    *)
      echo "ERROR: Unknown argument: $arg" >&2
      echo "Usage: $0 [--yes|-y]" >&2
      exit 1
      ;;
  esac
done

STATE_DIR="${SCRIPT_DIR}/.state"
MANIFEST="${STATE_DIR}/students.txt"

mkdir -p "$STATE_DIR"

acquire_lock() {
  if ( set -o noclobber; echo "$$" > "$LOCK_FILE" ) 2>/dev/null; then
    trap 'rm -f "$LOCK_FILE"' EXIT
  else
    local holder
    holder="$(cat "$LOCK_FILE" 2>/dev/null || echo unknown)"
    echo "ERROR: Another lifecycle operation holds the lock ($LOCK_FILE, pid=$holder)"
    exit 1
  fi
}

confirm_deploy() {
  case "${YES}" in
    true|True|TRUE|yes|Yes|YES|1) return 0 ;;
  esac
  if [[ -t 0 ]]; then
    local ans
    read -r -p "Deploy workshop (hub=${HUB_GUID}, students=${NUM_STUDENTS})? [y/N] " ans
    [[ "$ans" =~ ^[Yy]([Ee][Ss])?$ ]] || { echo "Aborted."; exit 1; }
  else
    echo "ERROR: Refusing non-interactive deploy without YES=true or --yes"
    exit 1
  fi
}

# -----------------------------------------------------------------
# Fail-fast prerequisite checks
# -----------------------------------------------------------------
for cmd in podman oc jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: $cmd is required but not found. Run: make setup"
    exit 1
  fi
done

if [[ ! -d "$AGNOSTICD_ROOT" ]]; then
  echo "ERROR: AgnosticD v2 not found at $AGNOSTICD_ROOT"
  echo "Clone it: git clone https://github.com/tosin2013/agnosticd-v2.git $AGNOSTICD_ROOT"
  exit 1
fi

if [[ ! -f "$AGNOSTICD_ROOT/bin/agd" ]]; then
  echo "ERROR: agd CLI not found. Run: cd $AGNOSTICD_ROOT && ./bin/agd setup"
  exit 1
fi

# Hard block: LINBIT registry credentials required for LINSTOR (drbd.io pull secret)
SECRETS_YML="${AGNOSTICD_ROOT}/../agnosticd-v2-secrets/secrets.yml"
if [[ ! -f "$SECRETS_YML" ]]; then
  echo "ERROR: AgnosticD secrets file not found: $SECRETS_YML"
  echo "Create it and set linbit_registry_username / linbit_registry_password."
  exit 1
fi
if ! python3 -c "
import sys, yaml
p = sys.argv[1]
d = yaml.safe_load(open(p)) or {}
u = (d.get('linbit_registry_username') or '').strip()
w = (d.get('linbit_registry_password') or '').strip()

def is_placeholder(v):
    if not v:
        return True
    low = v.lower()
    if v.startswith('<') or v.endswith('>'):
        return True
    if 'your linbit' in low or 'change_me' in low or 'changeme' in low:
        return True
    if low in ('xxx', 'xxxx', 'todo', 'example', 'placeholder'):
        return True
    return False

sys.exit(1 if is_placeholder(u) or is_placeholder(w) else 0)
" "$SECRETS_YML"; then
  echo "ERROR: LINBIT registry credentials missing or still placeholders in:"
  echo "  $SECRETS_YML"
  echo "Replace <Your LINBIT ...> with real registry login values:"
  echo "  linbit_registry_username: your-linbit-login"
  echo "  linbit_registry_password: your-linbit-password"
  echo "These create the in-cluster drbd.io pull secret (drbdiocred) for LINSTOR."
  echo "Run: make check   # or edit secrets.yml then re-deploy"
  exit 1
fi

acquire_lock
confirm_deploy

# Workshop identity for lifecycle scripts / audit (M4-18)
echo "guid=${HUB_GUID}" > "${STATE_DIR}/workshop-state"

# -----------------------------------------------------------------
# Copy vars files into agnosticd-v2-vars/ (agd expects them there)
# Copy, not symlink — symlinks break inside containers (see deploy-hardening.md)
# -----------------------------------------------------------------
echo "Copying vars files into $AGNOSTICD_VARS ..."
mkdir -p "$AGNOSTICD_VARS"
cp "$SCRIPT_DIR/vars/hub/linbit-hub.yaml" "$AGNOSTICD_VARS/${HUB_CONFIG_NAME}.yml"
cp "$SCRIPT_DIR/vars/student/linbit-student.yaml" "$AGNOSTICD_VARS/${STUDENT_CONFIG_NAME}.yml"

cd "$AGNOSTICD_ROOT"

# -----------------------------------------------------------------
# Phase 1: Deploy hub cluster
# -----------------------------------------------------------------
if [[ "$DEPLOY_HUB" == "true" ]]; then
  echo "============================================================"
  echo "Phase 1: Deploying hub cluster ($HUB_GUID)"
  echo "  Config: openshift-cluster (HA: 3 CP + 2 Workers)"
  echo "  Workloads: cert-manager, auth, RHACM, Showroom"
  echo "============================================================"
  AGNOSTICD_ROOT="$AGNOSTICD_ROOT" "$SCRIPT_DIR/run-agd.sh" provision \
    -g "$HUB_GUID" \
    -c "$HUB_CONFIG_NAME" \
    -a "$ACCOUNT"

  echo ""
  echo "Hub cluster deployed successfully."
fi

# -----------------------------------------------------------------
# Phase 2: Extract hub API URL and create a service-account token
# -----------------------------------------------------------------
echo "============================================================"
echo "Phase 2: Extracting hub credentials for RHACM import"
echo "============================================================"

HUB_OUTPUT="${AGNOSTICD_ROOT}/../agnosticd-v2-output/${HUB_GUID}"

KUBECONFIG_PATH=""
for candidate in \
  "${HUB_OUTPUT}/openshift-cluster_${HUB_GUID}_kubeconfig" \
  "${HUB_OUTPUT}/kubeconfig" \
  "${HUB_OUTPUT}/ocp4-cluster/auth/kubeconfig" \
  "${HUB_OUTPUT}/auth/kubeconfig"; do
  if [[ -f "$candidate" ]]; then
    KUBECONFIG_PATH="$candidate"
    break
  fi
done

# Fallback: any kubeconfig AgnosticD wrote under the hub output dir
if [[ -z "$KUBECONFIG_PATH" ]]; then
  KUBECONFIG_PATH="$(find "$HUB_OUTPUT" -maxdepth 2 -type f \( -name '*_kubeconfig' -o -name 'kubeconfig' \) 2>/dev/null | head -1 || true)"
fi

if [[ -z "$KUBECONFIG_PATH" || ! -f "$KUBECONFIG_PATH" ]]; then
  echo "ERROR: Hub kubeconfig not found under $HUB_OUTPUT"
  echo "Ensure the hub cluster ($HUB_GUID) is deployed."
  ls -la "$HUB_OUTPUT" 2>/dev/null || true
  exit 1
fi

export KUBECONFIG="$KUBECONFIG_PATH"
echo "Using kubeconfig: $KUBECONFIG_PATH"

HUB_API_URL=$(oc whoami --show-server 2>/dev/null)
echo "Hub API: $HUB_API_URL"

echo "Waiting for hub API..."
for i in $(seq 1 30); do
  if oc get nodes &>/dev/null; then
    echo "Hub cluster API is reachable."
    break
  fi
  sleep 10
done

oc get namespace rhacm-import-sa 2>/dev/null || \
  oc create namespace rhacm-import-sa

oc get sa rhacm-import -n rhacm-import-sa 2>/dev/null || \
  oc create sa rhacm-import -n rhacm-import-sa

oc get clusterrolebinding rhacm-import-binding 2>/dev/null || \
  oc create clusterrolebinding rhacm-import-binding \
    --clusterrole=cluster-admin \
    --serviceaccount=rhacm-import-sa:rhacm-import

HUB_TOKEN=$(oc create token rhacm-import -n rhacm-import-sa --duration=24h)

echo "Hub token extracted (24h TTL)."
echo "$HUB_API_URL" > "$STATE_DIR/hub_api_url"
echo "$HUB_TOKEN"   > "$STATE_DIR/hub_token"

unset KUBECONFIG

# -----------------------------------------------------------------
# Phase 3: Deploy student clusters with hub credentials injected
# -----------------------------------------------------------------
echo "============================================================"
echo "Phase 3: Deploying $NUM_STUDENTS student cluster(s)"
echo "  Method:    ${STUDENT_DEPLOY_METHOD}"
echo "  Topology:  TNA (2 primary + 1 arbiter)"
echo "  Workloads: cert-manager, LINBIT SDS (field-content), RHACM import"
echo "============================================================"

STUDENT_VARS_SRC="$SCRIPT_DIR/vars/student/linbit-student.yaml"

sed_inplace() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

inject_hub_credentials() {
  local student_num="$1"
  local guid="${BASE_GUID}-s${student_num}"
  local student_vars_file="${AGNOSTICD_VARS}/linbit-student-${student_num}.yml"

  cp "$STUDENT_VARS_SRC" "$student_vars_file"

  sed_inplace "s|^ocp4_workload_rhacm_import_hub_api_url:.*|ocp4_workload_rhacm_import_hub_api_url: \"${HUB_API_URL}\"|" "$student_vars_file"
  sed_inplace "s|^ocp4_workload_rhacm_import_hub_token:.*|ocp4_workload_rhacm_import_hub_token: \"${HUB_TOKEN}\"|" "$student_vars_file"
  sed_inplace "s|^ocp4_workload_rhacm_import_student_cluster_name:.*|ocp4_workload_rhacm_import_student_cluster_name: \"${guid}\"|" "$student_vars_file"

  echo "$student_vars_file"
}

> "$MANIFEST"

deploy_student_ipi() {
  local student_num="$1"
  local guid="${BASE_GUID}-s${student_num}"
  local config_name="linbit-student-${student_num}"

  echo "$guid" >> "$MANIFEST"
  echo "==> Deploying student cluster ($guid) via IPI ..."

  inject_hub_credentials "$student_num" > /dev/null

  AGNOSTICD_ROOT="$AGNOSTICD_ROOT" "$SCRIPT_DIR/run-agd.sh" provision \
    -g "$guid" \
    -c "$config_name" \
    -a "$ACCOUNT"

  echo "==> Student cluster ($guid) deployed and imported into RHACM."
}

deploy_student_agent() {
  local student_num="$1"
  local guid="${BASE_GUID}-s${student_num}"

  echo "$guid" >> "$MANIFEST"
  echo "==> Deploying student TNA cluster ($guid) via agent-based installer ..."

  local ansible_dir="${REPO_ROOT}/ansible"
  if [[ "${USE_ANSIBLE:-true}" == "true" && -f "${ansible_dir}/playbooks/deploy-tna-student.yml" ]]; then
    ANSIBLE_CONFIG="${ansible_dir}/ansible.cfg" ansible-playbook \
      "${ansible_dir}/playbooks/deploy-tna-student.yml" \
      -e tna_guid="$guid" \
      -e tna_base_domain="${BASE_DOMAIN}" \
      -e tna_aws_region="${AWS_REGION:-us-east-2}" \
      -e tna_owner="${OWNER:-tosin@redhat.com}"
  else
    "$SCRIPT_DIR/deploy-tna.sh" \
      --guid "$guid" \
      --account "$ACCOUNT" \
      --region "${AWS_REGION:-us-east-2}" \
      --domain "${BASE_DOMAIN}"
  fi

  echo "==> Student TNA cluster ($guid) deployed."
}

deploy_student() {
  local student_num="$1"
  case "${STUDENT_DEPLOY_METHOD}" in
    agent-based|agent|tna)
      deploy_student_agent "$student_num"
      ;;
    ipi|agnosticd|legacy)
      deploy_student_ipi "$student_num"
      ;;
    *)
      echo "ERROR: Unknown STUDENT_DEPLOY_METHOD: ${STUDENT_DEPLOY_METHOD}" >&2
      echo "Use 'agent-based' (default) or 'ipi'" >&2
      exit 1
      ;;
  esac
}

if [[ "$PARALLEL" == "true" ]]; then
  for i in $(seq 1 "$NUM_STUDENTS"); do
    inject_hub_credentials "$i" > /dev/null
  done
  pids=()
  for i in $(seq 1 "$NUM_STUDENTS"); do
    deploy_student "$i" &
    pids+=($!)
  done
  echo "Waiting for $NUM_STUDENTS parallel deployments..."
  failed=0
  for pid in "${pids[@]}"; do
    if ! wait "$pid"; then
      echo "ERROR: Process $pid failed"
      failed=$((failed + 1))
    fi
  done
  if (( failed > 0 )); then
    echo "ERROR: $failed/$NUM_STUDENTS student provisioning(s) failed."
    exit 1
  fi
else
  for i in $(seq 1 "$NUM_STUDENTS"); do
    deploy_student "$i"
  done
fi

# -----------------------------------------------------------------
# Phase 4: Deploy per-student Showroom instances on the hub (Model A)
# Each student gets a dedicated Showroom namespace on the hub cluster,
# configured with their own cluster's API URL and credentials.
# -----------------------------------------------------------------
echo "============================================================"
echo "Phase 4: Deploying per-student Showroom instances on hub"
echo "============================================================"

export KUBECONFIG="$KUBECONFIG_PATH"

SHOWROOM_GIT_REPO="${SHOWROOM_GIT_REPO:-https://github.com/tosin2013/openshift-tnf-edge-storage.git}"
SHOWROOM_GIT_REF="${SHOWROOM_GIT_REF:-main}"
SHOWROOM_IMAGE="${SHOWROOM_IMAGE:-quay.io/rhpds/openshift-showroom:latest}"
SHOWROOM_TERMINAL_IMAGE="${SHOWROOM_TERMINAL_IMAGE:-quay.io/rhpds/openshift-showroom-terminal-ocp:latest}"

STUDENT_OUTPUT_ROOT="${AGNOSTICD_ROOT}/../agnosticd-v2-output"

deploy_student_showroom() {
  local student_num="$1"
  local student_guid="${BASE_GUID}-s${student_num}"
  local ns="showroom-student-${student_num}"

  # Discover student cluster credentials
  local student_output="${STUDENT_OUTPUT_ROOT}/${student_guid}"
  local student_kubeadmin_pw=""
  local student_api_url=""
  local student_ingress_domain=""

  # Find kubeadmin password
  for pw_file in \
    "${student_output}/auth/kubeadmin-password" \
    "${student_output}/ocp4-cluster/auth/kubeadmin-password"; do
    if [[ -f "$pw_file" ]]; then
      student_kubeadmin_pw="$(cat "$pw_file")"
      break
    fi
  done
  [[ -n "$student_kubeadmin_pw" ]] || { echo "WARN: kubeadmin-password not found for $student_guid"; student_kubeadmin_pw="check-deployment-output"; }

  # Find student API URL from deployment info
  local deploy_info="${student_output}/deployment_info.txt"
  if [[ -f "$deploy_info" ]]; then
    student_api_url="$(grep '^api_url=' "$deploy_info" | cut -d= -f2-)"
  fi
  # Fallback: construct from GUID and base domain
  if [[ -z "$student_api_url" ]]; then
    local base_domain="${BASE_DOMAIN:-${ACCOUNT}.opentlc.com}"
    student_api_url="https://api.${student_guid}.${base_domain}:6443"
  fi

  student_ingress_domain="$(echo "$student_api_url" | sed 's|https://api\.|apps.|; s|:6443||')"

  echo "==> Student $student_num Showroom (ns=$ns)"
  echo "    API:     $student_api_url"
  echo "    Ingress: $student_ingress_domain"

  # Create namespace
  oc create namespace "$ns" 2>/dev/null || true
  oc label namespace "$ns" purpose=showroom student="student-${student_num}" --overwrite

  # ConfigMap with Antora user_data for this student's cluster
  cat <<CMEOF | oc apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-user-data
  namespace: ${ns}
data:
  guid: "${student_guid}"
  openshift_cluster_ingress_domain: "${student_ingress_domain}"
  api_url: "${student_api_url}"
  admin_password: "${student_kubeadmin_pw}"
CMEOF

  # Showroom Deployment
  cat <<DEPLEOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom
  namespace: ${ns}
  labels:
    app: showroom
    student: student-${student_num}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: showroom
  template:
    metadata:
      labels:
        app: showroom
        student: student-${student_num}
    spec:
      containers:
        - name: showroom
          image: ${SHOWROOM_IMAGE}
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: GIT_REPO_URL
              value: "${SHOWROOM_GIT_REPO}"
            - name: GIT_REPO_REF
              value: "${SHOWROOM_GIT_REF}"
            - name: GUID
              valueFrom:
                configMapKeyRef:
                  name: showroom-user-data
                  key: guid
          envFrom:
            - configMapRef:
                name: showroom-user-data
        - name: terminal
          image: ${SHOWROOM_TERMINAL_IMAGE}
          ports:
            - containerPort: 7681
              name: terminal
          env:
            - name: OC_LOGIN_COMMAND
              value: "oc login ${student_api_url} -u kubeadmin -p '${student_kubeadmin_pw}' --insecure-skip-tls-verify"
---
apiVersion: v1
kind: Service
metadata:
  name: showroom
  namespace: ${ns}
spec:
  selector:
    app: showroom
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: terminal
      port: 7681
      targetPort: 7681
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: showroom
  namespace: ${ns}
  labels:
    app: showroom
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: showroom
    weight: 100
  port:
    targetPort: http
DEPLEOF

  local route_host
  route_host="$(oc get route showroom -n "$ns" -o jsonpath='{.spec.host}' 2>/dev/null || echo "pending")"
  echo "    Showroom URL: https://${route_host}"
}

for i in $(seq 1 "$NUM_STUDENTS"); do
  deploy_student_showroom "$i"
done

unset KUBECONFIG

# -----------------------------------------------------------------
# Summary
# -----------------------------------------------------------------
echo ""
echo "============================================================"
echo "Deployment Complete"
echo "============================================================"
echo "Hub cluster:      $HUB_GUID"
echo "Hub API:          $HUB_API_URL"
echo "Student clusters: $NUM_STUDENTS"
echo ""
echo "Student Showroom URLs:"
for i in $(seq 1 "$NUM_STUDENTS"); do
  KUBECONFIG="$KUBECONFIG_PATH" oc get route showroom \
    -n "showroom-student-${i}" \
    -o jsonpath="  Student ${i}: https://{.spec.host}" 2>/dev/null
  echo ""
done
echo ""
cat "$MANIFEST"
echo ""
echo "RHACM:   KUBECONFIG=$KUBECONFIG_PATH oc get managedclusters"
