#!/usr/bin/env bash
# ===================================================================
# LINBIT Edge Storage Workshop — Full Deployment
# Deploys a hub cluster (RHACM + Showroom) then N student TNA clusters,
# each auto-imported into hub RHACM.
#
# Prerequisites:
#   - Run: make setup (or ./bootstrap.sh) to install prereqs and configure
#   - agnosticd-v2 cloned and agd setup completed
#   - secrets-<ACCOUNT>.yml filled in with AWS credentials
#   - Pull secret at the configured path
#   - Real linbit_registry_username / linbit_registry_password in
#     agnosticd-v2-secrets/secrets.yml (placeholders hard-fail this script)
#
# Usage:
#   ./agnosticd/deploy.sh                       # use config.yml defaults
#   NUM_STUDENTS=4 ./agnosticd/deploy.sh        # override student count
#   DEPLOY_HUB=false ./agnosticd/deploy.sh      # students only (hub exists)
#   PARALLEL=true ./agnosticd/deploy.sh         # deploy students in parallel
#   YES=true ./agnosticd/deploy.sh              # non-interactive confirm
#   ./agnosticd/deploy.sh --yes                 # same
#   make deploy ARGS=--yes
# ===================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOCK_FILE="${SCRIPT_DIR}/.workshop-lock"

# -----------------------------------------------------------------
# Read config.yml (generated by onboard / bootstrap.sh)
# Environment variables take precedence over config file values.
# -----------------------------------------------------------------
CONFIG_FILE="${SCRIPT_DIR}/config.yml"
if [[ -f "$CONFIG_FILE" ]]; then
  while IFS=': ' read -r key value; do
    key=$(echo "$key" | tr -d ' ')
    value=$(echo "$value" | tr -d '"' | tr -d "'")
    [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
    upper_key=$(echo "$key" | tr '[:lower:]' '[:upper:]')
    if [[ -z "${!upper_key:-}" ]]; then
      export "$upper_key=$value"
    fi
  done < "$CONFIG_FILE"
fi

# Map config keys to script variables (env vars override config, config overrides defaults)
AGNOSTICD_ROOT="${AGNOSTICD_ROOT:-${AGNOSTICD_ROOT_CONFIG:-$HOME/Development/agnosticd-v2}}"
AGNOSTICD_ROOT="${AGNOSTICD_ROOT/#\~/$HOME}"
AGNOSTICD_VARS="${AGNOSTICD_ROOT}/../agnosticd-v2-vars"
ACCOUNT="${ACCOUNT:-${ACCOUNT_CONFIG:-sandbox2530}}"

DEPLOY_HUB="${DEPLOY_HUB:-true}"
HUB_GUID="${HUB_GUID:-linbit-hub}"
HUB_CONFIG_NAME="linbit-hub"

BASE_GUID="${BASE_GUID:-linbit}"
STUDENT_CONFIG_NAME="linbit-student"
NUM_STUDENTS="${NUM_STUDENTS:-2}"
PARALLEL="${PARALLEL:-false}"
YES="${YES:-false}"
WORKLOADS_ONLY="${WORKLOADS_ONLY:-false}"
# Skip hub provision when only attaching workloads to an existing student cluster
if [[ "${WORKLOADS_ONLY}" == "true" ]]; then
  DEPLOY_HUB=false
fi

# Student deploy method: "agent-based" (true TNA) or "ipi" (legacy 6-node via AgnosticD)
STUDENT_DEPLOY_METHOD="${STUDENT_DEPLOY_METHOD:-agent-based}"

# Instance profile: "standard" (m7a.4xlarge, no KVM) or "virt-enabled" (m5zn.metal, real KVM)
STUDENT_INSTANCE_PROFILE="${STUDENT_INSTANCE_PROFILE:-standard}"
case "$STUDENT_INSTANCE_PROFILE" in
  virt-enabled)
    CP_INSTANCE_TYPE="${CP_INSTANCE_TYPE:-m5zn.metal}"
    ;;
  *)
    CP_INSTANCE_TYPE="${CP_INSTANCE_TYPE:-m7a.4xlarge}"
    ;;
esac
export CP_INSTANCE_TYPE

# CLI flags
for arg in "$@"; do
  case "$arg" in
    --yes|-y) YES=true ;;
    *)
      echo "ERROR: Unknown argument: $arg" >&2
      echo "Usage: $0 [--yes|-y]" >&2
      exit 1
      ;;
  esac
done

STATE_DIR="${SCRIPT_DIR}/.state"
MANIFEST="${STATE_DIR}/students.txt"

mkdir -p "$STATE_DIR"

acquire_lock() {
  if ( set -o noclobber; echo "$$" > "$LOCK_FILE" ) 2>/dev/null; then
    trap 'rm -f "$LOCK_FILE"' EXIT
  else
    local holder
    holder="$(cat "$LOCK_FILE" 2>/dev/null || echo unknown)"
    echo "ERROR: Another lifecycle operation holds the lock ($LOCK_FILE, pid=$holder)"
    exit 1
  fi
}

confirm_deploy() {
  case "${YES}" in
    true|True|TRUE|yes|Yes|YES|1) return 0 ;;
  esac
  if [[ -t 0 ]]; then
    local ans
    read -r -p "Deploy workshop (hub=${HUB_GUID}, students=${NUM_STUDENTS})? [y/N] " ans
    [[ "$ans" =~ ^[Yy]([Ee][Ss])?$ ]] || { echo "Aborted."; exit 1; }
  else
    echo "ERROR: Refusing non-interactive deploy without YES=true or --yes"
    exit 1
  fi
}

# -----------------------------------------------------------------
# Fail-fast prerequisite checks
# -----------------------------------------------------------------
for cmd in podman oc jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: $cmd is required but not found. Run: make setup"
    exit 1
  fi
done

if [[ ! -d "$AGNOSTICD_ROOT" ]]; then
  echo "ERROR: AgnosticD v2 not found at $AGNOSTICD_ROOT"
  echo "Clone it: git clone https://github.com/tosin2013/agnosticd-v2.git $AGNOSTICD_ROOT"
  exit 1
fi

if [[ ! -f "$AGNOSTICD_ROOT/bin/agd" ]]; then
  echo "ERROR: agd CLI not found. Run: cd $AGNOSTICD_ROOT && ./bin/agd setup"
  exit 1
fi

# Hard block: LINBIT registry credentials required for LINSTOR (drbd.io pull secret)
SECRETS_YML="${AGNOSTICD_ROOT}/../agnosticd-v2-secrets/secrets.yml"
if [[ ! -f "$SECRETS_YML" ]]; then
  echo "ERROR: AgnosticD secrets file not found: $SECRETS_YML"
  echo "Create it and set linbit_registry_username / linbit_registry_password."
  exit 1
fi
if ! python3 -c "
import sys, yaml
p = sys.argv[1]
d = yaml.safe_load(open(p)) or {}
u = (d.get('linbit_registry_username') or '').strip()
w = (d.get('linbit_registry_password') or '').strip()

def is_placeholder(v):
    if not v:
        return True
    low = v.lower()
    if v.startswith('<') or v.endswith('>'):
        return True
    if 'your linbit' in low or 'change_me' in low or 'changeme' in low:
        return True
    if low in ('xxx', 'xxxx', 'todo', 'example', 'placeholder'):
        return True
    return False

sys.exit(1 if is_placeholder(u) or is_placeholder(w) else 0)
" "$SECRETS_YML"; then
  echo "ERROR: LINBIT registry credentials missing or still placeholders in:"
  echo "  $SECRETS_YML"
  echo "Replace <Your LINBIT ...> with real registry login values:"
  echo "  linbit_registry_username: your-linbit-login"
  echo "  linbit_registry_password: your-linbit-password"
  echo "These create the in-cluster drbd.io pull secret (drbdiocred) for LINSTOR."
  echo "Run: make check   # or edit secrets.yml then re-deploy"
  exit 1
fi

acquire_lock
confirm_deploy

# Workshop identity for lifecycle scripts / audit (M4-18)
echo "guid=${HUB_GUID}" > "${STATE_DIR}/workshop-state"

# -----------------------------------------------------------------
# Copy vars files into agnosticd-v2-vars/ (agd expects them there)
# Copy, not symlink — symlinks break inside containers (see deploy-hardening.md)
# -----------------------------------------------------------------
echo "Copying vars files into $AGNOSTICD_VARS ..."
mkdir -p "$AGNOSTICD_VARS"
cp "$SCRIPT_DIR/vars/hub/linbit-hub.yaml" "$AGNOSTICD_VARS/${HUB_CONFIG_NAME}.yml"
cp "$SCRIPT_DIR/vars/student/linbit-student.yaml" "$AGNOSTICD_VARS/${STUDENT_CONFIG_NAME}.yml"

cd "$AGNOSTICD_ROOT"

# -----------------------------------------------------------------
# Phase 1: Deploy hub cluster
# -----------------------------------------------------------------
if [[ "$DEPLOY_HUB" == "true" ]]; then
  echo "============================================================"
  echo "Phase 1: Deploying hub cluster ($HUB_GUID)"
  echo "  Config: openshift-cluster (HA: 3 CP + 2 Workers)"
  echo "  Workloads: cert-manager, auth, RHACM, Showroom"
  echo "============================================================"
  AGNOSTICD_ROOT="$AGNOSTICD_ROOT" "$SCRIPT_DIR/run-agd.sh" provision \
    -g "$HUB_GUID" \
    -c "$HUB_CONFIG_NAME" \
    -a "$ACCOUNT"

  echo ""
  echo "Hub cluster deployed successfully."
fi

# -----------------------------------------------------------------
# Phase 2: Extract hub API URL and create a service-account token
# -----------------------------------------------------------------
echo "============================================================"
echo "Phase 2: Extracting hub credentials for RHACM import"
echo "============================================================"

HUB_OUTPUT="${AGNOSTICD_ROOT}/../agnosticd-v2-output/${HUB_GUID}"

KUBECONFIG_PATH=""
for candidate in \
  "${HUB_OUTPUT}/openshift-cluster_${HUB_GUID}_kubeconfig" \
  "${HUB_OUTPUT}/kubeconfig" \
  "${HUB_OUTPUT}/ocp4-cluster/auth/kubeconfig" \
  "${HUB_OUTPUT}/auth/kubeconfig"; do
  if [[ -f "$candidate" ]]; then
    KUBECONFIG_PATH="$candidate"
    break
  fi
done

# Fallback: any kubeconfig AgnosticD wrote under the hub output dir
if [[ -z "$KUBECONFIG_PATH" ]]; then
  KUBECONFIG_PATH="$(find "$HUB_OUTPUT" -maxdepth 2 -type f \( -name '*_kubeconfig' -o -name 'kubeconfig' \) 2>/dev/null | head -1 || true)"
fi

if [[ -z "$KUBECONFIG_PATH" || ! -f "$KUBECONFIG_PATH" ]]; then
  echo "ERROR: Hub kubeconfig not found under $HUB_OUTPUT"
  echo "Ensure the hub cluster ($HUB_GUID) is deployed."
  ls -la "$HUB_OUTPUT" 2>/dev/null || true
  exit 1
fi

export KUBECONFIG="$KUBECONFIG_PATH"
echo "Using kubeconfig: $KUBECONFIG_PATH"

HUB_API_URL=$(oc whoami --show-server 2>/dev/null)
echo "Hub API: $HUB_API_URL"

echo "Waiting for hub API..."
for i in $(seq 1 30); do
  if oc get nodes &>/dev/null; then
    echo "Hub cluster API is reachable."
    break
  fi
  sleep 10
done

oc get namespace rhacm-import-sa 2>/dev/null || \
  oc create namespace rhacm-import-sa

oc get sa rhacm-import -n rhacm-import-sa 2>/dev/null || \
  oc create sa rhacm-import -n rhacm-import-sa

oc get clusterrolebinding rhacm-import-binding 2>/dev/null || \
  oc create clusterrolebinding rhacm-import-binding \
    --clusterrole=cluster-admin \
    --serviceaccount=rhacm-import-sa:rhacm-import

HUB_TOKEN=$(oc create token rhacm-import -n rhacm-import-sa --duration=24h)

echo "Hub token extracted (24h TTL)."
echo "$HUB_API_URL" > "$STATE_DIR/hub_api_url"
echo "$HUB_TOKEN"   > "$STATE_DIR/hub_token"

unset KUBECONFIG

# -----------------------------------------------------------------
# Phase 3: Deploy student clusters with hub credentials injected
# -----------------------------------------------------------------
echo "============================================================"
echo "Phase 3: Deploying $NUM_STUDENTS student cluster(s)"
echo "  Method:    ${STUDENT_DEPLOY_METHOD}"
echo "  Profile:   ${STUDENT_INSTANCE_PROFILE} (CP: ${CP_INSTANCE_TYPE})"
echo "  Topology:  TNA (2 primary + 1 arbiter)"
echo "  Workloads: cert-manager, LINBIT SDS (field-content), RHACM import"
echo "============================================================"

STUDENT_VARS_SRC="$SCRIPT_DIR/vars/student/linbit-student.yaml"

sed_inplace() {
  if [[ "$(uname -s)" == "Darwin" ]]; then
    sed -i '' "$@"
  else
    sed -i "$@"
  fi
}

inject_hub_credentials() {
  local student_num="$1"
  local guid="${BASE_GUID}-s${student_num}"
  local student_vars_file="${AGNOSTICD_VARS}/linbit-student-${student_num}.yml"

  cp "$STUDENT_VARS_SRC" "$student_vars_file"

  sed_inplace "s|^ocp4_workload_rhacm_import_hub_api_url:.*|ocp4_workload_rhacm_import_hub_api_url: \"${HUB_API_URL}\"|" "$student_vars_file"
  sed_inplace "s|^ocp4_workload_rhacm_import_hub_token:.*|ocp4_workload_rhacm_import_hub_token: \"${HUB_TOKEN}\"|" "$student_vars_file"
  sed_inplace "s|^ocp4_workload_rhacm_import_student_cluster_name:.*|ocp4_workload_rhacm_import_student_cluster_name: \"${guid}\"|" "$student_vars_file"

  # virt-enabled profile: disable nested KVM emulation (real hardware KVM on m5.metal)
  if [[ "$STUDENT_INSTANCE_PROFILE" == "virt-enabled" ]]; then
    sed_inplace "s|^ocp4_workload_openshift_virtualization_enabled_nested_kvm:.*|ocp4_workload_openshift_virtualization_enabled_nested_kvm: false|" "$student_vars_file"
  fi

  echo "$student_vars_file"
}

# Wait for Field Content parent + child ArgoCD Applications (helm/templates/applications.yaml)
wait_field_content_apps() {
  local kubeconfig="$1"
  local ns="openshift-gitops"
  local apps=(
    field-content
    field-content-linstor-operator
    field-content-storageclasses
    field-content-sample-database
    field-content-sample-vm
    field-content-userinfo
  )
  echo "    Waiting for ArgoCD Applications to become Healthy..."
  local i healthy app status
  for i in $(seq 1 90); do
    healthy=0
    for app in "${apps[@]}"; do
      status="$(KUBECONFIG="$kubeconfig" oc get application "$app" -n "$ns" \
        -o jsonpath='{.status.health.status}' 2>/dev/null || true)"
      sync="$(KUBECONFIG="$kubeconfig" oc get application "$app" -n "$ns" \
        -o jsonpath='{.status.sync.status}' 2>/dev/null || true)"
      [[ "$status" == "Healthy" && "$sync" == "Synced" ]] && healthy=$((healthy + 1))
    done
    if (( healthy == ${#apps[@]} )); then
      echo "    All Field Content Applications are Healthy."
      return 0
    fi
    sleep 20
  done
  echo "WARN: Timed out waiting for ArgoCD Applications (Healthy=${healthy}/${#apps[@]})."
  KUBECONFIG="$kubeconfig" oc get applications -n "$ns" \
    -o custom-columns='NAME:.metadata.name,SYNC:.status.sync.status,HEALTH:.status.health.status' 2>/dev/null || true
  return 0
}

apply_linstor_passphrase() {
  local kubeconfig="$1"
  local pass
  pass="$(python3 -c "import yaml,sys; d=yaml.safe_load(open(sys.argv[1])) or {}; print((d.get('linstor_encryption_passphrase') or '').strip())" "$SECRETS_YML")"
  if [[ -z "$pass" ]]; then
    echo "WARN: linstor_encryption_passphrase missing from secrets.yml — skip Module 5 pre-seed."
    return 0
  fi
  echo "    Applying LINSTOR encryption passphrase on the student cluster..."
  local i
  for i in $(seq 1 60); do
    if KUBECONFIG="$kubeconfig" oc get deploy linstor-controller -n linbit-sds &>/dev/null; then
      KUBECONFIG="$kubeconfig" oc wait --for=condition=available \
        deploy/linstor-controller -n linbit-sds --timeout=120s >/dev/null 2>&1 || true
      KUBECONFIG="$kubeconfig" oc exec -n linbit-sds deploy/linstor-controller -- \
        linstor encryption create-passphrase --passphrase "$pass" >/dev/null 2>&1 || true
      return 0
    fi
    sleep 10
  done
  echo "WARN: linstor-controller not ready; passphrase not applied."
}

> "$MANIFEST"

deploy_student_ipi() {
  local student_num="$1"
  local guid="${BASE_GUID}-s${student_num}"
  local config_name="linbit-student-${student_num}"

  echo "$guid" >> "$MANIFEST"
  echo "==> Deploying student cluster ($guid) via IPI ..."

  inject_hub_credentials "$student_num" > /dev/null

  AGNOSTICD_ROOT="$AGNOSTICD_ROOT" "$SCRIPT_DIR/run-agd.sh" provision \
    -g "$guid" \
    -c "$config_name" \
    -a "$ACCOUNT"

  echo "==> Student cluster ($guid) deployed and imported into RHACM."
}

deploy_student_agent() {
  local student_num="$1"
  local guid="${BASE_GUID}-s${student_num}"

  echo "$guid" >> "$MANIFEST"
  echo "==> Deploying student TNA cluster ($guid) via agent-based installer ..."

  local ansible_dir="${REPO_ROOT}/ansible"
  if [[ "${USE_ANSIBLE:-true}" == "true" && -f "${ansible_dir}/playbooks/deploy-tna-student.yml" ]]; then
    local nested_kvm="true"
    [[ "$STUDENT_INSTANCE_PROFILE" == "virt-enabled" ]] && nested_kvm="false"
    ANSIBLE_CONFIG="${ansible_dir}/ansible.cfg" ansible-playbook \
      "${ansible_dir}/playbooks/deploy-tna-student.yml" \
      -e tna_guid="$guid" \
      -e tna_base_domain="${BASE_DOMAIN}" \
      -e tna_aws_region="${AWS_REGION:-us-east-2}" \
      -e tna_owner="${OWNER:-tosin@redhat.com}" \
      -e tna_cp_instance_type="${CP_INSTANCE_TYPE}" \
      -e tna_enabled_nested_kvm="${nested_kvm}" \
      -e tna_linstor_install_method=helm
  else
    "$SCRIPT_DIR/deploy-tna.sh" \
      --guid "$guid" \
      --account "$ACCOUNT" \
      --region "${AWS_REGION:-us-east-2}" \
      --domain "${BASE_DOMAIN}"
  fi

  echo "==> Student TNA cluster ($guid) deployed."
}

deploy_student_workloads() {
  local student_num="$1"
  local guid="${BASE_GUID}-s${student_num}"
  local student_output="${AGNOSTICD_ROOT}/../agnosticd-v2-output/${guid}"

  echo "==> Deploying workloads on $guid via openshift-workloads ..."

  local student_kc=""
  for kc in "${student_output}/auth/kubeconfig" \
            "${student_output}/agent-assets/iso-build/auth/kubeconfig"; do
    [[ -f "$kc" ]] && student_kc="$kc" && break
  done
  if [[ -z "$student_kc" ]]; then
    echo "ERROR: kubeconfig not found for $guid under $student_output"
    return 1
  fi

  local api_url
  api_url=$(KUBECONFIG="$student_kc" oc whoami --show-server 2>/dev/null)
  echo "    Cluster API: $api_url"

  KUBECONFIG="$student_kc" oc create sa workload-deployer -n kube-system 2>/dev/null || true
  KUBECONFIG="$student_kc" oc adm policy add-cluster-role-to-user cluster-admin \
    -z workload-deployer -n kube-system 2>/dev/null || true
  local api_token
  api_token=$(KUBECONFIG="$student_kc" oc create token workload-deployer -n kube-system --duration=24h)

  local aws_key aws_secret
  aws_key=$(aws configure get aws_access_key_id 2>/dev/null || echo "")
  aws_secret=$(aws configure get aws_secret_access_key 2>/dev/null || echo "")

  local base_domain="${BASE_DOMAIN:-${ACCOUNT}.opentlc.com}"
  local hosted_zone_id=""
  hosted_zone_id=$(aws route53 list-hosted-zones-by-name \
    --dns-name "${base_domain}" --max-items 1 \
    --query "HostedZones[0].Id" --output text 2>/dev/null | sed 's|/hostedzone/||' || echo "")
  echo "    HostedZoneID: $hosted_zone_id"

  local wl_vars="${AGNOSTICD_VARS}/linbit-student-${student_num}-workloads.yml"
  local linbit_user linbit_pass
  linbit_user="$(python3 -c "import yaml,sys; d=yaml.safe_load(open(sys.argv[1])) or {}; print((d.get('linbit_registry_username') or '').strip())" "$SECRETS_YML")"
  linbit_pass="$(python3 -c "import yaml,sys; d=yaml.safe_load(open(sys.argv[1])) or {}; print((d.get('linbit_registry_password') or '').strip())" "$SECRETS_YML")"

  inject_hub_credentials "$student_num" > /dev/null

  cat > "$wl_vars" <<WLEOF
---
config: openshift-workloads
cloud_provider: none

requirements_content:
  collections:
    - name: https://github.com/rhpds/core_workloads.git
      type: git
      version: main

clusters:
  default:
    api_url: "${api_url}"
    api_token: "${api_token}"

openshift_api_url: "${api_url}"
openshift_api_key: "${api_token}"

workloads:
  - agnosticd.core_workloads.ocp4_workload_cert_manager
  - agnosticd.core_workloads.ocp4_workload_field_content

ocp4_workload_cert_manager_channel: stable-v1
ocp4_workload_cert_manager_aws_hostedzoneid: "${hosted_zone_id}"
ocp4_workload_cert_manager_aws_region: "${AWS_REGION:-us-east-2}"
ocp4_workload_cert_manager_aws_access_key_id: "${aws_key}"
ocp4_workload_cert_manager_aws_secret_access_key: "${aws_secret}"
ocp4_workload_cert_manager_use_catalog_snapshot: false
ocp4_workload_cert_manager_install_ingress_certificates: true
ocp4_workload_cert_manager_install_api_certificates: false

# GitOps + CNV are installed by ansible/roles/tna_student_cluster phase 7b.
# Field Content deploys helm/ via ArgoCD (linstor-operator, SCs, sample-db/vm, userinfo).
ocp4_workload_field_content_gitops_repo_url: "https://github.com/tosin2013/openshift-tnf-edge-storage.git"
ocp4_workload_field_content_gitops_repo_path: "helm"
ocp4_workload_field_content_gitops_repo_revision: "main"
ocp4_workload_field_content_namespace: openshift-gitops
ocp4_workload_field_content_helm_values:
  components:
    linstorOperator:
      registrySecret:
        create: true
        name: drbdiocred
        server: drbd.io
        username: "${linbit_user}"
        password: "${linbit_pass}"
WLEOF

  echo "    Vars: $wl_vars"

  local wl_config="linbit-student-${student_num}-workloads"
  AGNOSTICD_ROOT="$AGNOSTICD_ROOT" "$SCRIPT_DIR/run-agd.sh" provision \
    -g "${guid}-wl" \
    -c "$wl_config" \
    -a "$ACCOUNT"

  echo "==> Workloads deployed on $guid."
  wait_field_content_apps "$student_kc"
  apply_linstor_passphrase "$student_kc"
}

deploy_student() {
  local student_num="$1"
  if [[ "${WORKLOADS_ONLY}" == "true" ]]; then
    echo "${BASE_GUID}-s${student_num}" >> "$MANIFEST"
    echo "==> WORKLOADS_ONLY: skipping TNA installer for student ${student_num}"
    deploy_student_workloads "$student_num"
    return
  fi
  case "${STUDENT_DEPLOY_METHOD}" in
    agent-based|agent|tna)
      deploy_student_agent "$student_num"
      deploy_student_workloads "$student_num"
      ;;
    ipi|agnosticd|legacy)
      deploy_student_ipi "$student_num"
      ;;
    *)
      echo "ERROR: Unknown STUDENT_DEPLOY_METHOD: ${STUDENT_DEPLOY_METHOD}" >&2
      echo "Use 'agent-based' (default) or 'ipi'" >&2
      exit 1
      ;;
  esac
}

if [[ "$PARALLEL" == "true" ]]; then
  for i in $(seq 1 "$NUM_STUDENTS"); do
    inject_hub_credentials "$i" > /dev/null
  done
  pids=()
  for i in $(seq 1 "$NUM_STUDENTS"); do
    deploy_student "$i" &
    pids+=($!)
  done
  echo "Waiting for $NUM_STUDENTS parallel deployments..."
  failed=0
  for pid in "${pids[@]}"; do
    if ! wait "$pid"; then
      echo "ERROR: Process $pid failed"
      failed=$((failed + 1))
    fi
  done
  if (( failed > 0 )); then
    echo "ERROR: $failed/$NUM_STUDENTS student provisioning(s) failed."
    exit 1
  fi
else
  for i in $(seq 1 "$NUM_STUDENTS"); do
    deploy_student "$i"
  done
fi

# -----------------------------------------------------------------
# Phase 4: Deploy per-student Showroom instances on the hub (Model A)
# Clones the exact resource structure that AgnosticD deploys:
#   SA, RoleBinding, 3 ConfigMaps, PVC, Deployment (3 containers),
#   Service, Route.
# Each student gets a dedicated namespace with their own cluster creds.
# -----------------------------------------------------------------
echo "============================================================"
echo "Phase 4: Deploying per-student Showroom instances on hub"
echo "============================================================"

export KUBECONFIG="$KUBECONFIG_PATH"

SHOWROOM_GIT_REPO="${SHOWROOM_GIT_REPO:-https://github.com/tosin2013/openshift-tnf-edge-storage.git}"
SHOWROOM_GIT_REF="${SHOWROOM_GIT_REF:-main}"
SHOWROOM_CONTENT_IMAGE="${SHOWROOM_CONTENT_IMAGE:-ghcr.io/rhpds/showroom-content:prod}"
SHOWROOM_TERMINAL_IMAGE="${SHOWROOM_TERMINAL_IMAGE:-quay.io/rhpds/openshift-showroom-terminal-ocp:latest}"
SHOWROOM_NGINX_IMAGE="${SHOWROOM_NGINX_IMAGE:-quay.io/rhpds/nginx:1.25}"

STUDENT_OUTPUT_ROOT="${AGNOSTICD_ROOT}/../agnosticd-v2-output"

deploy_student_showroom() {
  local student_num="$1"
  local student_guid="${BASE_GUID}-s${student_num}"
  local ns="showroom-student-${student_num}"

  # --- Discover student cluster credentials ---
  local student_output="${STUDENT_OUTPUT_ROOT}/${student_guid}"
  local student_kubeadmin_pw=""
  local student_api_url=""
  local student_ingress_domain=""

  for pw_file in \
    "${student_output}/auth/kubeadmin-password" \
    "${student_output}/ocp4-cluster/auth/kubeadmin-password"; do
    [[ -f "$pw_file" ]] && student_kubeadmin_pw="$(cat "$pw_file")" && break
  done
  [[ -n "$student_kubeadmin_pw" ]] || { echo "WARN: kubeadmin-password not found for $student_guid"; student_kubeadmin_pw="check-deployment-output"; }

  local deploy_info="${student_output}/deployment_info.txt"
  if [[ -f "$deploy_info" ]]; then
    student_api_url="$(grep '^api_url=' "$deploy_info" | cut -d= -f2-)"
  fi
  if [[ -z "$student_api_url" ]]; then
    local base_domain="${BASE_DOMAIN:-${ACCOUNT}.opentlc.com}"
    student_api_url="https://api.${student_guid}.${base_domain}:6443"
  fi
  student_ingress_domain="$(echo "$student_api_url" | sed 's|https://api\.|apps.|; s|:6443||')"

  local linstor_pass
  linstor_pass="$(python3 -c "import yaml,sys; d=yaml.safe_load(open(sys.argv[1])) or {}; print((d.get('linstor_encryption_passphrase') or '').strip())" "$SECRETS_YML" 2>/dev/null || true)"
  [[ -n "$linstor_pass" ]] || linstor_pass="CHANGE_ME"

  echo "==> Student $student_num Showroom (ns=$ns)"
  echo "    API:     $student_api_url"
  echo "    Ingress: $student_ingress_domain"

  # --- Namespace + RBAC ---
  oc create namespace "$ns" 2>/dev/null || true
  oc label namespace "$ns" purpose=showroom student="student-${student_num}" --overwrite
  oc create sa showroom -n "$ns" 2>/dev/null || true
  oc create rolebinding edit-showroom-sa -n "$ns" \
    --clusterrole=edit --serviceaccount="${ns}:showroom" 2>/dev/null || true

  # --- ConfigMap: showroom-userdata (student-specific credentials) ---
  cat <<UDEOF | oc apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-userdata
  namespace: ${ns}
data:
  user_data.yml: |
    "guid": "${student_guid}"
    "openshift_cluster_ingress_domain": "${student_ingress_domain}"
    "openshift_api_url": "${student_api_url}"
    "openshift_api_server_url": "${student_api_url}"
    "openshift_cluster_admin_password": "${student_kubeadmin_pw}"
    "openshift_cluster_admin_username": "kubeadmin"
    "openshift_console_url": "https://console-openshift-console.${student_ingress_domain}"
    "openshift_cluster_console_url": "https://console-openshift-console.${student_ingress_domain}"
    "bastion_ssh_user_name": "lab-user"
    "linstor_encryption_passphrase": "${linstor_pass}"
UDEOF

  # --- ConfigMap: showroom-proxy-config (nginx reverse proxy) ---
  cat <<'NGEOF' | oc apply -n "$ns" -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-proxy-config
data:
  nginx.conf: |
    events {}
    error_log /dev/stdout info;
    http {
      include /etc/nginx/mime.types;
      proxy_cache off;
      expires -1;
      proxy_cache_path /dev/null keys_zone=mycache:10m;
      map $http_upgrade $connection_upgrade {
          default upgrade;
          '' close;
      }
      server {
        listen 8080;
        absolute_redirect off;
        location / {
          index index.html;
          root /data/www;
        }
        location /content/ {
          proxy_pass http://localhost:8000;
          rewrite ^/content/(.*)$ /$1 break;
          expires off;
          proxy_cache off;
          proxy_pass_request_headers on;
          proxy_set_header Accept-Encoding "gzip";
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        location /terminal/ {
          proxy_pass http://localhost:7681;
          rewrite ^/terminal/(.*)$ /$1 break;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_read_timeout 43200000;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_set_header X-NginX-Proxy true;
        }
      }
    }
NGEOF

  # --- PVC: terminal home directory ---
  cat <<PVCEOF | oc apply -f -
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: showroom-terminal-lab-user-home
  namespace: ${ns}
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: gp3-csi
  resources:
    requests:
      storage: 5Gi
PVCEOF

  # --- Service + Route (created before Deployment so we can read the hostname) ---
  cat <<SVCEOF | oc apply -f -
apiVersion: v1
kind: Service
metadata:
  name: showroom
  namespace: ${ns}
spec:
  selector:
    app.kubernetes.io/name: showroom
  ports:
    - name: web
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: showroom
  namespace: ${ns}
  annotations:
    haproxy.router.openshift.io/timeout: 1h
    haproxy.router.openshift.io/timeout-tunnel: 1h
spec:
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: showroom
    weight: 100
  port:
    targetPort: 8080
SVCEOF

  # Wait for Route to get a hostname
  local route_host=""
  for _rw in $(seq 1 10); do
    route_host="$(oc get route showroom -n "$ns" -o jsonpath='{.spec.host}' 2>/dev/null || true)"
    [[ -n "$route_host" ]] && break
    sleep 2
  done
  [[ -n "$route_host" ]] || route_host="showroom-${ns}.apps.placeholder"
  echo "    Route:   https://${route_host}"

  # --- ConfigMap: showroom-index (HTML shell with route-specific iframes) ---
  cat <<IDXEOF | oc apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: showroom-index
  namespace: ${ns}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Showroom — Student ${student_num}</title>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <link rel="stylesheet" type="text/css" href="split.css">
        <link rel="stylesheet" type="text/css" href="tabs.css">
      </head>
      <body>
        <div class="content">
          <div class="split left">
            <iframe id="doc" src="https://${route_host}/content" width="100%" style="border:none;"></iframe>
          </div>
          <div class="split right">
            <div class="tab">
              <button class="tablinks" onclick="openTerminal(event, 'terminal_tab1')" id="defaultOpen" tabindex="0">Terminal 1</button>
            </div>
            <div id="terminal_tab1" class="tabcontent">
              <iframe id="terminal_01" src="https://${route_host}/terminal" width="100%" style="border:none;"></iframe>
            </div>
          </div>
        </div>
        <script>
          document.getElementById("defaultOpen").click();
          function openTerminal(evt, tabName) {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
            for (i = 0; i < tabcontent.length; i++) { tabcontent[i].style.display = "none"; }
            tablinks = document.getElementsByClassName("tablinks");
            for (i = 0; i < tablinks.length; i++) { tablinks[i].className = tablinks[i].className.replace(" active", ""); }
            document.getElementById(tabName).style.display = "block";
            evt.currentTarget.className += "active";
          }
        </script>
        <script src="https://unpkg.com/split.js/dist/split.min.js"></script>
        <script>
          Split(['.left', '.right'], { sizes: [45,55] });
        </script>
      </body>
    </html>
  split.css: |
    * { box-sizing: border-box; height:100%; }
    body { margin: 0; height:100%; }
    .content { width: 100%; height: 100%; padding: 0; display: flex; border-top: 1px solid Gainsboro; }
    .split { width:100%; height:100%; padding: 5px; }
    .gutter { height: 98%; background-color: #eee; background-repeat: no-repeat; background-position: 50%; }
    .gutter.gutter-horizontal { background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAeCAYAAADkftS9AAAAIklEQVQoU2M4c+bMfxAGAgYYmwGrIIiDjrELjpo5aiZeMwF+yNnOs5KSvgAAAABJRU5ErkJggg=='); cursor: col-resize; }
  tabs.css: |
    .tab { overflow: hidden; border: 1px solid #ccc; background-color: #f1f1f1; height: 50px; }
    .tab button { background-color: inherit; float: left; border: none; outline: none; cursor: pointer; padding: 14px 16px; transition: 0.3s; }
    .tab button:hover { background-color: #ddd; }
    .tab button.active { background-color: #ccc; }
    .tabcontent { display: none; padding: 6px 12px; border: 1px solid #ccc; border-top: none; height: calc(100% - 50px); }
IDXEOF

  # --- Deployment (3 containers: nginx, content, terminal) ---
  cat <<DEPEOF | oc apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  name: showroom
  namespace: ${ns}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: showroom
  template:
    metadata:
      labels:
        app.kubernetes.io/name: showroom
    spec:
      serviceAccountName: showroom
      containers:
        - name: nginx
          image: ${SHOWROOM_NGINX_IMAGE}
          ports:
            - containerPort: 8080
              name: web
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: content
              mountPath: /data/www
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-pid
              mountPath: /var/run
        - name: content
          image: ${SHOWROOM_CONTENT_IMAGE}
          env:
            - name: GIT_REPO_URL
              value: "${SHOWROOM_GIT_REPO}"
            - name: GIT_REPO_REF
              value: "${SHOWROOM_GIT_REF}"
            - name: ANTORA_PLAYBOOK
              value: site.yml
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet: { path: /, port: 8000 }
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /, port: 8000 }
            periodSeconds: 10
          volumeMounts:
            - name: user-data
              mountPath: /user_data/
            - name: showroom
              mountPath: /showroom/
        - name: terminal
          image: ${SHOWROOM_TERMINAL_IMAGE}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GUID
              value: "${student_guid}"
          ports:
            - containerPort: 7681
          resources:
            requests: { cpu: 50m, memory: 256Mi }
            limits:   { cpu: 500m, memory: 1Gi }
          volumeMounts:
            - name: terminal-lab-user-home
              mountPath: /home/lab-user
      volumes:
        - name: showroom
          emptyDir: {}
        - name: user-data
          configMap:
            name: showroom-userdata
        - name: content
          configMap:
            name: showroom-index
        - name: nginx-config
          configMap:
            name: showroom-proxy-config
        - name: nginx-pid
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
        - name: terminal-lab-user-home
          persistentVolumeClaim:
            claimName: showroom-terminal-lab-user-home
DEPEOF

  echo "    Showroom URL: https://${route_host}"
}

for i in $(seq 1 "$NUM_STUDENTS"); do
  deploy_student_showroom "$i"
done

unset KUBECONFIG

# -----------------------------------------------------------------
# Summary
# -----------------------------------------------------------------
echo ""
echo "============================================================"
echo "Deployment Complete"
echo "============================================================"
echo "Hub cluster:      $HUB_GUID"
echo "Hub API:          $HUB_API_URL"
echo "Student clusters: $NUM_STUDENTS"
echo ""
echo "Student Showroom URLs:"
for i in $(seq 1 "$NUM_STUDENTS"); do
  KUBECONFIG="$KUBECONFIG_PATH" oc get route showroom \
    -n "showroom-student-${i}" \
    -o jsonpath="  Student ${i}: https://{.spec.host}" 2>/dev/null
  echo ""
done
echo ""
cat "$MANIFEST"
echo ""
echo "RHACM:   KUBECONFIG=$KUBECONFIG_PATH oc get managedclusters"
