{{- if .Values.operator.enabled }}
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
  namespace: {{ .Values.operator.namespace }}
{{- $pullSecret := .Values.registrySecret.name | default "drbdiocred" }}
{{- if or .Values.registrySecret.create .Values.registrySecret.name }}
spec:
  controller:
    podTemplate:
      spec:
        imagePullSecrets:
          - name: {{ $pullSecret }}
  csiController:
    podTemplate:
      spec:
        imagePullSecrets:
          - name: {{ $pullSecret }}
  csiNode:
    podTemplate:
      spec:
        imagePullSecrets:
          - name: {{ $pullSecret }}
  satellite:
    podTemplate:
      spec:
        imagePullSecrets:
          - name: {{ $pullSecret }}
        tolerations:
          - key: linbit.com/arbiter
            operator: Exists
            effect: NoSchedule
{{- else }}
spec:
  satellite:
    podTemplate:
      spec:
        tolerations:
          - key: linbit.com/arbiter
            operator: Exists
            effect: NoSchedule
{{- end }}
{{- end }}
