{{- if .Values.operator.enabled }}
apiVersion: piraeus.io/v1
kind: LinstorCluster
metadata:
  name: linstorcluster
  namespace: {{ .Values.operator.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
{{- $pullSecret := .Values.registrySecret.name | default "drbdiocred" }}
spec:
  tolerations:
    - key: linbit.com/arbiter
      operator: Exists
      effect: NoSchedule
{{- if or .Values.registrySecret.create .Values.registrySecret.name }}
  controller:
    podTemplate:
      spec:
        imagePullSecrets:
          - name: {{ $pullSecret }}
  csiController:
    podTemplate:
      spec:
        imagePullSecrets:
          - name: {{ $pullSecret }}
  csiNode:
    podTemplate:
      spec:
        imagePullSecrets:
          - name: {{ $pullSecret }}
{{- end }}
{{- end }}
