{{- if .Values.operator.enabled }}
apiVersion: piraeus.io/v1
kind: LinstorSatelliteConfiguration
metadata:
  name: storage-pool-config
  namespace: {{ .Values.operator.namespace }}
spec:
  {{- $pullSecret := .Values.registrySecret.name | default "drbdiocred" }}
  {{- if or .Values.registrySecret.create .Values.registrySecret.name }}
  podTemplate:
    spec:
      imagePullSecrets:
        - name: {{ $pullSecret }}
  {{- end }}
  storagePools:
    - name: {{ .Values.storagePool.name }}
      {{- if eq .Values.storagePool.providerType "LVM_THIN" }}
      lvmThinPool:
        volumeGroup: linstor_{{ .Values.storagePool.name }}
      source:
        hostDevices:
        {{- range .Values.storagePool.devicePaths }}
          - {{ . }}
        {{- end }}
      {{- end }}
{{- end }}

